const fs = require('fs');
const path = require('path');

const ja = {
  "page_title": "テトリス学習とリプレイシステム | コア・ドキュメント",
  "nav_foreword": "はじめに",
  "nav_intro": "背景",
  "nav_rules": "問題",
  "nav_origin": "提案",
  "nav_journey": "システム",
  "nav_replay": "Replay分析",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "実装",
  "nav_tech": "今後の課題",
  "brand_title": "テトリス学習システム",
  "cover_h1": "対戦型テトリス初心者の振り返りを支援するリプレイ分析システム",
  "cover_author": "by WANHENG（バンコウ）",
  "cover_github": "GitHub",
  "cover_download": "ダウンロード",
  "cover_label": "コア・ドキュメント",
  "cover_lead": "対戦型テトリスでは，プレイヤーは高速な時間制約の中で，落下位置，回転，攻撃，防御を判断し続ける必要がある。しかし初心者は，自分の操作のどこに問題があったのかを試合後に把握しにくく，反復練習だけでは非効率な操作習慣を固定してしまう可能性がある。そこで本研究では，リプレイデータを用いて操作と判断を可視化し，必要に応じてガイドブック型の練習へ接続する学習支援システムを開発した。",
  "cover_flow_1_title": "はじめに",
  "cover_flow_1_desc": "まず，テトリスがなぜ競技性を持っているのかを分かりやすい言葉で説明する。",
  "cover_flow_2_title": "問題",
  "cover_flow_2_desc": "高速な判断と操作戦略が必要である一方，初心者は自分のミスや次に学ぶべき内容を把握しにくい。",
  "cover_flow_3_title": "システム",
  "cover_flow_3_desc": "リプレイ分析を中心に，操作の問題を可視化し，必要な練習へ導く学習支援を行う。",
  "cover_flow_4_title": "システム構造",
  "cover_flow_4_desc": "最後に，ゲーム，データ収集，AI分析，マルチプレイ対戦，そしてツールチェーンがどのように組み合わされているかを説明する。",
  
  "intro_kicker": "背景：対戦型テトリスの競技性",
  "intro_h2": "対戦型テトリスでは，短時間で複数の判断を同時に行う必要がある。",
  "intro_p1": "多くの人にとって，テトリスは「落ちてくるブロックを並べ，一列揃えて消す」ゲームとして認識されている。しかし対戦型テトリスでは，ライン消去は得点だけでなく相手への攻撃にもつながる。プレイヤーは自分の盤面を整えながら，相手へ送る攻撃量と，自分が受ける攻撃への対応を同時に考える必要がある。",
  "intro_p2": "さらに，プレイヤーは NEXT と Hold を利用して数手先を予測し，T-Spin，Combo，Back-to-Back，相殺などの要素を状況に応じて選択する。つまり，対戦型テトリスは単純な反射ゲームではなく，配置判断，攻撃，防御，先読みが短時間に圧縮されたリアルタイム課題である。",
  "intro_p3": "そのため，初心者が上達するには，単に何度もプレイするだけではなく，自分のプレイを後から見直し，どの判断が良く，どの判断が問題だったのかを理解することが重要になる。本研究では，この「振り返り」に焦点を当てる。",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "回転時にブロックの位置をわずかにずらし，通常は入らない隙間へ挿入する仕組みである。",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "Tブロックを回転させて特定の地形（くぼみ）に入れ，少ないライン消去で高い攻撃価値を生み出す代表的な技術である。",
  "intro_fig1": "攻撃を受けると，プレッシャーはまず「アタックゲージ（攻撃バー）」に表示され，自身のライン消去によって相殺する機会がある。",
  "intro_fig2": "プレッシャーを処理できなかった場合，攻撃はフィールド底部の「お邪魔ブロック」に変換され，その後の展開を大きく変化させる。",
  "intro_footnote": "これらの1v1の画像は基本的なメカニクスを示している。攻撃は突然現れるのではなく，まずプレッシャーとして表示される。自身のライン消去で相殺できなければ，そのプレッシャーは盤面に入り込み，処理すべき「お邪魔ブロック」となる。",

  "rules_kicker": "問題：初心者の振り返りの難しさ",
  "rules_h2": "初心者は，単なるリプレイ再生だけでは「なぜ負けたのか」「どこを改善すべきか」を理解しにくい。",
  "rules_p1": "既存の学習方法として，Wiki，動画チュートリアル，コミュニティでの解説などが存在する。これらは一般的な知識や熟練者のプレイを学ぶには有効であるが，プレイヤー自身の対局における具体的な判断やミスを示すことは難しいという限界がある。",
  "rules_p2": "また，従来のリプレイ機能は対局を時系列で再生できるが，各手の評価，攻撃・防御への影響，より良い選択肢までは明示しない。そのため初心者は，映像を見返しても「どの場面で判断を誤ったのか」「どのような置き方がより良かったのか」を自力で判断しにくい。",
  "rules_p3": "盤面の高さ，空洞，攻撃のタイミング，相殺の判断などが同時に影響するため，問題の原因が一つの操作だけにあるとは限らないことも多い。したがって，リプレイを単なる録画ではなく，一手ごとの判断を可視化する分析データとして扱う支援が必要である。",
  "rules_stack_1_title": "一般知識の限界",
  "rules_stack_1_desc": "Wikiや動画は概念説明には適しているが，自身の対局のどの手が問題だったのかまでは示しにくい。",
  "rules_stack_2_title": "従来のリプレイ機能の限界",
  "rules_stack_2_desc": "再生だけでは，各手の評価や別の選択肢までは示されにくい。",
  "rules_stack_3_title": "非効率な習慣",
  "rules_stack_3_desc": "反復練習だけでは，安定してはいるが非効率な操作を固定してしまう可能性がある。",
  "rules_stack_4_title": "必要な支援",
  "rules_stack_4_desc": "リプレイを，単なる録画ではなく，判断を可視化する分析データとして扱う必要がある。",
  "rules_demo_wall_title": "従来の学習方法の限界",
  "rules_demo_wall_desc": "一般的な解説は「何をすべきか」を説明できるが，「この対局において，どの一手がなぜ悪かったのか」を自動的に示すことはできない。",
  "rules_demo_tspin_title": "研究上の問題定義",
  "rules_demo_tspin_desc": "初心者が自身の対局を振り返り，ミスや改善点を発見するためには，プレイデータに基づく可視化と分析が必要である。",
  
  "source_tetris_title": "対戦型テトリスにおける操作戦略の差異",
  "source_tetris_desc": "Lindstedt and Gray（2020）は，テトリスを高速なリアルタイム課題として位置づけ，初心者と熟練者の回転操作戦略に差異があることを示している。この知見は，対戦型テトリスにおける上達が単なる反復練習や反応速度だけでなく，認知的負荷を伴う判断過程と関係することを示唆している。",

  "origin_kicker": "提案：リプレイ分析による振り返り支援",
  "origin_h2": "本研究の目的は，初心者が自身のプレイを理解し，改善点を発見できるようにすることである。",
  "origin_p1": "本研究では，対戦型テトリス初心者が自身の対局を振り返り，ミスや改善点を理解できるようにすることを目的とする。そのために，プレイ中の操作記録，盤面状態，攻撃・防御の状況を保存し，試合後に一手ごとの判断を可視化するリプレイ分析システムを開発した。",
  "origin_p2": "そこで本研究では，リプレイを単なる再生機能ではなく，プレイヤー自身の判断を分析するためのデータとして扱う。盤面状態，操作記録，攻撃・防御の状況を結び付けることで，初心者が「どの一手が問題だったのか」を確認できるようにする。",
  "origin_p3": "また，分析結果を理解するための前提知識としてGuidebookを用意し，T-SpinやComboなどの基礎技術を小さなシミュレーションで確認できるようにする。これにより，Replay分析で見つかった課題を次の練習へ接続する。",
  "origin_aside_h3": "研究の中心",
  "origin_aside_p": "中心となるのはReplay分析である。Guidebookは独立した要素ではなく，分析結果を理解するための前提知識を補う機能として位置づける。AIもそれ自体が目的ではなく，一手ごとの比較と評価を行う分析手段として扱う。",

  "source_gla_title": "Game Learning Analytics に基づくリプレイ分析",
  "source_gla_desc": "Alonso-Fernández et al.（2022）は，シリアスゲームにおけるプレイヤーのインタラクションデータを収集・分析・可視化する Game Learning Analytics の枠組みを示している。本研究では，この知見に基づき，テトリスのリプレイデータを学習過程の分析対象として扱う。",

  "journey_kicker": "システムの全体像",
  "journey_h2": "Replay分析を中心に，基礎理解，試合後分析，改善練習を一つの流れとして接続する。",
  "journey_step1_h3": "対局データを記録する",
  "journey_step1_p": "プレイ中の盤面，落下位置，消去，攻撃，時間，操作結果を保存し，試合後に分析可能な形式にする。",
  "journey_step2_h3": "一手ごとに可視化する",
  "journey_step2_p": "リプレイ画面で盤面，タイムライン，攻撃状況，AI推奨手を並べ，どの場面が問題だったかを確認できるようにする。",
  "journey_step3_h3": "改善点を発見する",
  "journey_step3_p": "実際の選択と推奨手を比較し，地形悪化，攻撃機会の損失，相殺判断の遅れなどを特定する。",
  "journey_step4_h3": "Guidebookで補助学習する",
  "journey_step4_p": "分析結果を理解するために必要なT-Spin，Combo，相殺などを，小さなシミュレーションで確認できるようにする。",
  "journey_step5_h3": "変化を確認する",
  "journey_step5_p": "単局サマリーやレーダーチャートで，速度，攻撃，効率，安定性などの変化を長期的に確認する。",

  "replay_kicker": "Replay分析：一手ごとの判断を可視化する",
  "replay_h2": "AIは対局中に操作を指示するのではなく，試合後にプレイヤーの判断を分析する。",
  "replay_p1": "本システムでは，AIが対局中に操作を指示するのではなく，試合後にプレイヤーの選択を分析する。これにより，プレイヤー本来の判断を妨げずに，対局後の振り返りを支援できる。",
  "replay_p2": "Replayでは，各手の盤面状態，落下位置，ライン消去，攻撃量，地形変化を確認できる。プレイヤーは試合全体をただ眺めるのではなく，どの一手がその後の不利な状況につながったのかを段階的に追うことが可能である。",
  "replay_p3": "AI評価では，プレイヤーの実際の置き方と，探索によって得られた推奨手を比較する。差が大きい手を候補として示すことで，初心者が「この場面では何を見落としていたのか」を考えやすくする。",
  "replay_p4": "また，単局サマリーやレーダーチャートにより，速度，攻撃，効率，構造，安定性，視野などを確認できる。これにより，個別のミスだけでなく，長期的な成長傾向も把握できる。",
  "replay_aside_h3": "設計原則",
  "replay_aside_p": "AIはプレイヤーの操作権を奪うものではなく，試合後のコーチとして機能する。目的は「代わりにプレイすること」ではなく，「プレイヤーが自身の判断を理解できるようにすること」である。",
  "replay_fig1_cap": "Replayのインターフェースは，盤面，タイムライン，AIの推奨，解説パネルを統合し，プレイヤーが自身の選択を段階的に確認できるよう支援する。",
  "replay_fig2_cap": "1ゲームのサマリーデータにより，そのゲームの全体的なパフォーマンスを把握できる。",
  "replay_fig3_cap": "レーダーチャートは，様々な能力の指標を比較しやすい一つの形状に圧縮する。",
  "replay_note_h3": "1ゲームから長期的な変化へ",
  "replay_note_p": "1ゲームのサマリーは「このゲームで何が起きたか」に答え，レーダーチャートは「能力構造にどのような特徴があるか」に答える。プレイヤーが繰り返しリプレイ分析を行うことで，毎回の経験を長期的な成長へと繋げることが可能となる。",

  "guide_kicker": "Guidebook：分析結果を理解するための基礎学習",
  "guide_h2": "Guidebookは，Replay分析を理解するための補助教材として位置づける。",
  "guide_p1": "初心者がReplay分析の結果を理解するためには，T-Spin，Combo，相殺，攻撃価値，NEXT/Holdなどの基礎知識が必要である。これらを知らないままでは，AIが示した推奨手や評価の意味を理解しにくくなる。",
  "guide_p2": "そこでGuidebookでは，基本ルールや代表的なテクニックを小さな章に分割し，アニメーションと固定局面のシミュレーションで確認できるようにする。目的は知識を増やすこと自体ではなく，Replayで見つかった課題を理解し，次の練習へつなげることである。",
  "guide_p3": "たとえばReplayでT-Spinの機会を逃していた場合，GuidebookのT-Spin章に戻り，構造と操作を固定局面で確認できる。このようにGuidebookは，Replay分析を中心とした学習サイクルを支える補助機能として機能する。",
  "guide_annotation_title": "Guidebook画面の構成",
  "guide_annotation_desc": "本文，章カード，シミュレーション入口を1つの画面に統合し，学習の流れをそのまま提示する。",
  "guide_module_1_title": "基礎知識",
  "guide_module_1_desc": "攻撃力，お邪魔ブロック，相殺，B2B，Comboなどのルールを明確にする。",
  "guide_module_2_title": "操作セクション",
  "guide_module_2_desc": "Wall Kick，Combo，T-Spin Doubleなどを学習可能な小さな章に分割する。",
  "guide_module_3_title": "シミュレーション演習",
  "guide_module_3_desc": "プレイヤーは固定された局面に移行し，実際の操作で目標アクションを1度完了させる。",
  "guide_module_4_title": "フィードバック",
  "guide_module_4_desc": "システムが目標達成を判定し，アクションが正しく成立したかをプレイヤーに通知する。",

  "arch_kicker": "実装：プレイデータの記録・評価・可視化",
  "arch_h2": "Replay分析を実現するために，各手の状態を記録し，評価し，画面上に可視化する。",
  "arch_title_entry": "分析に必要なデータ",
  "arch_entry_1": "盤面スナップショット",
  "arch_entry_2": "操作と落下位置",
  "arch_entry_3": "消去・攻撃・相殺",
  "arch_entry_4": "速度と手順",
  "arch_connector": "対局中に記録したデータを，試合後にReplay画面で再構成し，AI評価と可視化に利用する。",
  "arch_layer_1_title": "ゲーム実行レイヤー",
  "arch_layer_1_i1": "10 × 20の盤面",
  "arch_layer_1_i2": "SRS回転とWall Kick",
  "arch_layer_1_i4": "Combo / B2B / T-Spin判定",
  "arch_layer_2_title": "データ収集レイヤー",
  "arch_layer_2_i1": "毎手の落下位置",
  "arch_layer_2_i2": "盤面スナップショット",
  "arch_layer_2_i3": "ライン消去と攻撃",
  "arch_layer_2_i4": "時間，スピードと操作結果",
  "arch_layer_3_title": "分析・可視化レイヤー",
  "arch_layer_3_i1": "AI推奨手との比較",
  "arch_layer_3_i2": "タイムライン表示",
  "arch_layer_3_i3": "単局サマリー",
  "arch_layer_3_i4": "レーダーチャート",
  "arch_flow_1_title": "対局データ",
  "arch_flow_1_desc": "実際のプレイで生じた毎手の記録",
  "arch_flow_2_title": "分析アルゴリズム",
  "arch_flow_2_desc": "候補ルートを探索し，評価関数でスコアリング",
  "arch_flow_3_title": "Replayの視覚化",
  "arch_flow_3_desc": "タイムライン，推奨落下位置，データパネル，レーダーチャート",
  "arch_support_title": "実装補足",
  "arch_support_1_title": "三言語ローカライズ",
  "arch_support_1_desc": "中国語 / 日本語 / 英語",
  "arch_support_2_title": "入力対応",
  "arch_support_2_desc": "キーボードとコントローラー",
  "arch_support_3_title": "素材とUI",
  "arch_support_3_desc": "ロビー，盤面，リプレイ画面",
  "arch_support_4_title": "オンライン対戦",
  "arch_support_4_desc": "オンライン対戦データも収集している",

  "tech_kicker": "今後の課題：評価実験と分析精度の改善",
  "tech_h2": "今後は，本システムが初心者の振り返りを有効に支援できるかを検証する必要がある。",
  "tech_p1": "現段階では，リプレイ分析の仕組みと可視化インターフェースを実装している。次の課題は，初心者がこのシステムを使用することで，自身のミスや改善点をより理解しやすくなるかを評価することである。",
  "tech_p2": "評価方法としては，システム使用前後で，プレイヤーが自身のミスを説明できるか，推奨手の意味を理解できるか，同じ種類のミスを減らせるかを確認する必要がある。アンケートや簡単なプレイ課題を組み合わせることで，学習支援としての有効性を検証できる。",
  "tech_p3": "また，AI評価の精度も改善の余地がある。現状の評価関数は，盤面の高さ，空洞，攻撃機会などをもとにルートを評価するが，初心者にとって理解しやすい説明へ変換するには，評価理由をより明確に示す必要がある。",
  "tech_p4": "さらに，オンライン対戦機能は現時点では主題ではなく，将来的に多様なプレイデータを収集し，分析対象を広げるための拡張機能として位置づける。本研究ではまず，リプレイ分析による初心者の振り返り支援に焦点を絞る。",
  "tech_card_1_title": "評価実験",
  "tech_card_1_desc": "初心者がミスや改善点を説明しやすくなるかを確認する。",
  "tech_card_2_title": "分析精度",
  "tech_card_2_desc": "推奨手と評価関数が初心者の改善に役立つかを検証する。",
  "tech_card_3_title": "説明性",
  "tech_card_3_desc": "なぜその手が良いのかを，盤面指標と自然な説明で示す。",
  "tech_card_4_title": "Guidebook連携",
  "tech_card_4_desc": "分析結果から関連する基礎章へ自然に接続する。",
  "tech_card_5_title": "オンラインデータ",
  "tech_card_5_desc": "収集済みのオンライン対戦データを評価・分析に活用する。",

  "closing_label": "おわりに",
  "closing_h2": "本研究の中心は，初心者が自身の対局を理解し，改善点を発見するためのReplay分析支援である。",
  "closing_p": "従来は，初心者が従来のリプレイ機能を見返しても，具体的にどの判断が問題だったのかを理解しにくいという課題があった。そこで本研究では，盤面・操作・攻撃状況を記録し，試合後に一手ごとの判断を可視化するReplay分析システムを開発した。GuidebookやAI評価は，この中心目的を支えるための補助要素として位置づける。"
};

const zh = {
  "page_title": "俄罗斯方块学习与复盘系统 | 核心文档",
  "nav_foreword": "引言",
  "nav_intro": "背景",
  "nav_rules": "问题",
  "nav_origin": "提案",
  "nav_journey": "系统",
  "nav_replay": "Replay分析",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "架构",
  "nav_tech": "未来展望",
  "brand_title": "俄罗斯方块学习系统",
  "cover_h1": "面向对战型 Tetris 初学者的复盘分析支援系统",
  "cover_author": "by WANHENG（万恒）",
  "cover_github": "GitHub",
  "cover_download": "下载",
  "cover_label": "核心文档",
  "cover_lead": "在对战型 Tetris 中，玩家需要在短时间内持续判断方块落点、旋转、攻击与防守。然而初学者即使在赛后观看录像，也很难把握自己的操作究竟哪里出了问题；仅靠反复练习，容易固化低效的操作习惯。因此，本研究开发了一套学习支援系统，利用 replay 数据可视化玩家的操作与判断，并在此基础上引导玩家进行 Guidebook 式的针对性练习。",
  "cover_flow_1_title": "引言",
  "cover_flow_1_desc": "首先，以通俗的语言解释 Tetris 为什么具有竞技性。",
  "cover_flow_2_title": "问题",
  "cover_flow_2_desc": "尽管需要高速的判断与操作策略，但初学者很难把握自身的失误以及下一步该学什么。",
  "cover_flow_3_title": "系统",
  "cover_flow_3_desc": "以 Replay 分析为中心，可视化操作问题，并引导至必要的练习。",
  "cover_flow_4_title": "系统架构",
  "cover_flow_4_desc": "最后，说明游戏本体、数据采集、AI 分析、多人对战与工具链是如何组合的。",
  
  "intro_kicker": "背景：对战型 Tetris 的竞技性",
  "intro_h2": "对战型 Tetris 要求玩家在短时间内同时做出多项判断。",
  "intro_p1": "对许多人而言，Tetris 被认为是一个“把落下的方块排满一行并消除”的游戏。但在对战型 Tetris 中，消除行数不仅能得分，还会转化为对对手的攻击。玩家在整理自身盘面的同时，必须时刻权衡向对手发送的攻击量以及如何应对自己受到的攻击。",
  "intro_p2": "此外，玩家还需要利用 NEXT（预览）与 Hold（暂存）来预测几步之后的局面，并根据战况选择 T-Spin、Combo、Back-to-Back 或抵消等策略。换言之，对战型 Tetris 并非单纯的反射神经游戏，而是将放置判断、攻击、防守与前瞻规划压缩在极短时间内的实时任务。",
  "intro_p3": "因此，初学者若要提升水平，仅靠反复游玩是不够的，赛后回顾自己的对局、理解哪些判断做得好、哪些判断存在问题，显得尤为重要。本研究正是聚焦于这一“复盘”过程。",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "在旋转时使方块位置发生轻微偏移，从而将其插入正常情况下无法进入的空隙的机制。",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "通过旋转将 T 方块放入特定地形（凹陷处），以较少的消行产生较高攻击价值的代表性技术。",
  "intro_fig1": "受到攻击时，压力会首先显示在“攻击条”中，玩家有机会通过自身的消行来进行抵消。",
  "intro_fig2": "如果未能处理压力，攻击将转化为场地底部的“垃圾行”，从而大幅改变随后的战局。",
  "intro_footnote": "这些 1v1 的截图展示了基本机制：攻击并非凭空出现，而是先作为压力显示。若无法用自身的消行抵消，压力就会进入盘面，成为必须处理的“垃圾行”。",

  "rules_kicker": "问题：初学者复盘的困难性",
  "rules_h2": "初学者仅靠单纯的录像回放，很难理解“为什么输”以及“该改善哪里”。",
  "rules_p1": "现有的学习方法包括 Wiki、视频教程和社区解说等。这些资源在学习一般知识和观摩高手操作方面非常有效，但却很难指出玩家自身对局中具体的判断失误与问题所在。",
  "rules_p2": "另一方面，传统的 Replay 功能虽然可以按时间顺序回放对局，但并不会明确显示每一步的评价、对攻防的影响以及更好的替代方案。因此，初学者即使反复观看录像，也很难靠自己判断出“在哪个场景判断失误”以及“怎样放置会更好”。",
  "rules_p3": "由于盘面高度、空洞、攻击时机、抵消判断等因素会同时产生影响，问题的原因往往并不局限于某单一步骤。因此，不能仅仅将 Replay 视为单纯的录像，而是需要将其作为能够可视化每一步判断的分析数据来提供支援。",
  "rules_stack_1_title": "一般知识的局限",
  "rules_stack_1_desc": "Wiki和视频擅长解释概念，但难以指出玩家自身对局中哪一步存在问题。",
  "rules_stack_2_title": "传统 Replay 功能的局限",
  "rules_stack_2_desc": "仅靠回放录像，很难直接显示每一步的评价或其他更好的选择。",
  "rules_stack_3_title": "低效的操作习惯",
  "rules_stack_3_desc": "仅靠反复练习，可能会固化那些虽然稳定但效率低下的操作方式。",
  "rules_stack_4_title": "必要的支援",
  "rules_stack_4_desc": "需要将 Replay 视为可视化判断过程的分析数据，而非单纯的录像。",
  "rules_demo_wall_title": "传统学习方法的局限",
  "rules_demo_wall_desc": "一般的解说可以说明“应该怎么做”，但无法自动指出“在这场对局中，具体哪一步为什么不好”。",
  "rules_demo_tspin_title": "研究问题定义",
  "rules_demo_tspin_desc": "为了让初学者能够回顾自身的对局并发现失误与改善点，基于游玩数据的可视化与分析是不可或缺的。",
  
  "source_tetris_title": "对战型 Tetris 中的操作策略差异",
  "source_tetris_desc": "Lindstedt and Gray (2020) 将 Tetris 定位为高速实时任务，并指出初学者与熟练者在旋转操作策略上存在差异。这一研究表明，对战型 Tetris 的进步不仅依赖反复练习或反应速度，更与带有认知负荷的判断过程密切相关。",

  "origin_kicker": "提案：通过 Replay 分析支援复盘",
  "origin_h2": "本研究的目的是让初学者能够理解自身的游玩过程，并发现其中的改善点。",
  "origin_p1": "本研究旨在帮助对战型 Tetris 初学者回顾自身的对局，从而理解失误和改善点。为此，本系统会在游玩过程中保存操作记录、盘面状态以及攻防状况，并在赛后提供能够可视化每一步判断的 Replay 分析功能。",
  "origin_p2": "因此，本研究不将 Replay 视为单纯的播放功能，而是将其作为分析玩家自身判断的数据来处理。通过将盘面状态、操作记录与攻防状况相结合，使初学者能够确认“究竟是哪一步出了问题”。",
  "origin_p3": "同时，系统提供了 Guidebook 作为理解分析结果的前提知识补充，让玩家可以通过小型模拟来确认 T-Spin 或 Combo 等基础技术。由此，将 Replay 分析中发现的课题与下一步的练习相连接。",
  "origin_aside_h3": "研究的中心",
  "origin_aside_p": "研究的核心是 Replay 分析。Guidebook 并非独立存在，而是作为补充分析结果前提知识的辅助功能。AI 也不是目的本身，而是用于进行逐项比较与评价的分析手段。",

  "source_gla_title": "基于 Game Learning Analytics 的 Replay 分析",
  "source_gla_desc": "Alonso-Fernández et al. (2022) 提出了在严肃游戏（Serious Games）中收集、分析并可视化玩家交互数据的 Game Learning Analytics 框架。本研究基于这一理论，将 Tetris 的 replay 数据作为学习过程的分析对象。",

  "journey_kicker": "系统整体架构",
  "journey_h2": "以 Replay 分析为中心，将基础理解、赛后分析与改善练习连接为一个完整的流程。",
  "journey_step1_h3": "记录对局数据",
  "journey_step1_p": "保存游玩过程中的盘面、落点、消行、攻击、时间与操作结果，转化为赛后可分析的格式。",
  "journey_step2_h3": "可视化每一步判断",
  "journey_step2_p": "在 Replay 界面中并排显示盘面、时间线、攻击状况与 AI 推荐步骤，使玩家能确认问题出现的场景。",
  "journey_step3_h3": "发现改善点",
  "journey_step3_p": "通过对比实际选择与推荐步骤，定位地形恶化、攻击机会错失或抵消判断延迟等问题。",
  "journey_step4_h3": "通过 Guidebook 辅助学习",
  "journey_step4_p": "对于理解分析结果所必需的 T-Spin、Combo、抵消等概念，通过小型模拟让玩家进行确认。",
  "journey_step5_h3": "确认长期的变化",
  "journey_step5_p": "利用单局摘要与雷达图，长期观察速度、攻击、效率、稳定性等指标的变化。",

  "replay_kicker": "Replay 分析：可视化每一步的判断",
  "replay_h2": "AI 不会在对局中直接指示操作，而是在赛后分析玩家的判断。",
  "replay_p1": "在本系统中，AI 不会在对局中指示操作，而是负责在赛后分析玩家的选择。这样既不会干扰玩家原本的判断体验，又能有效支援赛后的复盘。",
  "replay_p2": "在 Replay 中，玩家可以确认每一步的盘面状态、落点、消行、攻击量以及地形变化。玩家不再只是干巴巴地观看比赛全程，而是可以分阶段追踪“是哪一步导致了后来的不利局面”。",
  "replay_p3": "在 AI 评价中，系统会将玩家的实际放置与通过搜索算法得出的推荐步骤进行比较。通过将差异较大的步骤作为候选问题提出，帮助初学者思考“在这个场景中，我忽略了什么”。",
  "replay_p4": "此外，借助单局摘要和雷达图，玩家可以确认速度、攻击、效率、结构、稳定性与视野等多项指标。借此不仅能发现个别失误，还能把握长期的成长趋势。",
  "replay_aside_h3": "设计原则",
  "replay_aside_p": "AI 不应剥夺玩家的操作权，而是作为赛后的教练发挥作用。其目的不是“代替玩家游玩”，而是“让玩家能够理解自身的判断”。",
  "replay_fig1_cap": "Replay 界面整合了盘面、时间线、AI 推荐与解说面板，帮助玩家分阶段检查自身的选择。",
  "replay_fig2_cap": "通过单局摘要数据，可以把握该局游戏的整体表现。",
  "replay_fig3_cap": "雷达图将各项能力指标压缩为一种易于比较的形状。",
  "replay_note_h3": "从单局到长期的变化",
  "replay_note_p": "单局摘要回答了“这局游戏发生了什么”，雷达图则回答了“能力结构有什么特征”。玩家通过反复进行 Replay 分析，即可将每一次的经验转化为长期的成长。",

  "guide_kicker": "Guidebook：用于理解分析结果的基础学习",
  "guide_h2": "Guidebook 被定位为理解 Replay 分析结果的辅助教材。",
  "guide_p1": "为了让初学者理解 Replay 分析的结果，T-Spin、Combo、抵消、攻击价值以及 NEXT/Hold 等基础知识是必不可少的。若缺乏这些知识，玩家将很难理解 AI 给出的推荐步骤与评价含义。",
  "guide_p2": "因此，Guidebook 将基本规则与代表性技术划分为小章节，并通过动画与固定局面的模拟来进行确认。其目的不在于单纯增加知识，而是为了理解 Replay 中发现的问题，并将其与下一步的练习相连接。",
  "guide_p3": "例如，如果在 Replay 中错失了 T-Spin 的机会，玩家可以返回 Guidebook 的 T-Spin 章节，在固定局面中确认其构造与操作。如此一来，Guidebook 就能作为辅助功能，支撑起以 Replay 分析为中心的学习循环。",
  "guide_annotation_title": "Guidebook 界面的构成",
  "guide_annotation_desc": "将正文、章节卡片与模拟入口整合在同一界面，直观呈现学习流程。",
  "guide_module_1_title": "基础知识",
  "guide_module_1_desc": "明确攻击力、垃圾行、抵消、B2B、Combo 等规则。",
  "guide_module_2_title": "操作章节",
  "guide_module_2_desc": "将 Wall Kick、Combo、T-Spin Double 等划分为可学习的小章节。",
  "guide_module_3_title": "模拟演练",
  "guide_module_3_desc": "玩家进入固定局面，通过实际操作完成一次目标动作。",
  "guide_module_4_title": "反馈",
  "guide_module_4_desc": "系统判定是否达成目标，通知玩家该动作是否正确成立。",

  "arch_kicker": "实现：游玩数据的记录、评价与可视化",
  "arch_h2": "为了实现 Replay 分析，系统会记录并评价每一步的状态，并在界面上进行可视化。",
  "arch_title_entry": "分析所需的数据",
  "arch_entry_1": "盘面快照",
  "arch_entry_2": "操作与落点",
  "arch_entry_3": "消行、攻击与抵消",
  "arch_entry_4": "速度与操作步骤",
  "arch_connector": "将在对局中记录的数据，于赛后在 Replay 界面中重构，并用于 AI 评价与可视化。",
  "arch_layer_1_title": "游戏运行层",
  "arch_layer_1_i1": "10 × 20 的盘面",
  "arch_layer_1_i2": "SRS 旋转与 Wall Kick",
  "arch_layer_1_i4": "Combo / B2B / T-Spin 判定",
  "arch_layer_2_title": "数据采集层",
  "arch_layer_2_i1": "每一步的落点",
  "arch_layer_2_i2": "盘面快照",
  "arch_layer_2_i3": "消行与攻击",
  "arch_layer_2_i4": "时间、速度与操作结果",
  "arch_layer_3_title": "分析与可视化层",
  "arch_layer_3_i1": "与 AI 推荐步骤的比较",
  "arch_layer_3_i2": "时间线显示",
  "arch_layer_3_i3": "单局摘要",
  "arch_layer_3_i4": "雷达图",
  "arch_flow_1_title": "对局数据",
  "arch_flow_1_desc": "实际游玩中产生的每步记录",
  "arch_flow_2_title": "分析算法",
  "arch_flow_2_desc": "搜索候选路线，并通过评价函数进行打分",
  "arch_flow_3_title": "Replay 的可视化",
  "arch_flow_3_desc": "时间线、推荐落点、数据面板、雷达图",
  "arch_support_title": "实现补充",
  "arch_support_1_title": "三语本地化",
  "arch_support_1_desc": "中文 / 日文 / 英文",
  "arch_support_2_title": "输入适配",
  "arch_support_2_desc": "键盘与手柄",
  "arch_support_3_title": "素材与UI",
  "arch_support_3_desc": "大厅、盘面、复盘界面",
  "arch_support_4_title": "在线对战",
  "arch_support_4_desc": "已在收集在线对战数据",

  "tech_kicker": "未来展望：评价实验与分析精度的提升",
  "tech_h2": "未来有必要验证本系统是否能有效支援初学者的复盘。",
  "tech_p1": "目前，系统已经实现了 Replay 分析的机制与可视化界面。接下来的课题是评价初学者在使用本系统后，是否能更容易地理解自身的失误与改善点。",
  "tech_p2": "作为评价方法，需要确认在系统使用前后，玩家能否解释自身的失误、能否理解推荐步骤的含义，以及能否减少同类失误的发生。通过结合问卷调查与简单的游玩任务，即可验证其作为学习支援工具的有效性。",
  "tech_p3": "此外，AI 评价的精度也有提升空间。目前的评价函数基于盘面高度、空洞、攻击机会等指标对路线进行打分；但若要将其转换为初学者易于理解的解说，则需要更明确地展示评价的具体理由。",
  "tech_p4": "进一步而言，在线对战功能目前并非研究主体，而是被定位为未来收集多样化游玩数据、扩大分析对象的扩展功能。本研究现阶段仍将重点聚焦于通过 Replay 分析来支援初学者的复盘。",
  "tech_card_1_title": "评价实验",
  "tech_card_1_desc": "确认初学者是否更容易解释失误与改善点。",
  "tech_card_2_title": "分析精度",
  "tech_card_2_desc": "验证推荐步骤与评价函数是否有助于初学者的水平提升。",
  "tech_card_3_title": "可解释性",
  "tech_card_3_desc": "利用盘面指标与自然语言，说明该步骤为何更优。",
  "tech_card_4_title": "Guidebook 联动",
  "tech_card_4_desc": "将分析结果自然地连接至相关的基础章节。",
  "tech_card_5_title": "在线数据",
  "tech_card_5_desc": "将已收集的在线对战数据应用于评价与分析。",

  "closing_label": "结语",
  "closing_h2": "本研究的核心，是为初学者理解自身对局、发现改善点提供 Replay 分析支援。",
  "closing_p": "以往，初学者即使反复观看传统的回放录像，也很难理解具体是哪一步判断出了问题。针对这一课题，本研究开发了记录盘面、操作与攻击状况，并在赛后可视化每一步判断的 Replay 分析系统。Guidebook 与 AI 评价皆作为支撑这一核心目的的辅助功能而存在。"
};

const en = {
  "page_title": "Tetris Learning & Replay System | Core Document",
  "nav_foreword": "Foreword",
  "nav_intro": "Background",
  "nav_rules": "Problem",
  "nav_origin": "Proposal",
  "nav_journey": "System",
  "nav_replay": "Replay Analysis",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "Architecture",
  "nav_tech": "Future Work",
  "brand_title": "Tetris Learning System",
  "cover_h1": "A Replay Analysis Support System for Beginner Competitive Tetris Players",
  "cover_author": "by WANHENG",
  "cover_github": "GitHub",
  "cover_download": "Download",
  "cover_label": "Core Document",
  "cover_lead": "In competitive Tetris, players must continuously make decisions regarding drop locations, rotations, attacks, and defense under severe time constraints. However, beginners find it difficult to grasp exactly where their operations went wrong after a match, and repetitive practice alone may solidify inefficient operational habits. Therefore, this research developed a learning support system that visualizes operations and decisions using replay data and connects players to Guidebook-style practice when necessary.",
  "cover_flow_1_title": "Foreword",
  "cover_flow_1_desc": "First, explain in plain language why Tetris possesses a competitive nature.",
  "cover_flow_2_title": "Problem",
  "cover_flow_2_desc": "Despite requiring rapid judgment and strategy, beginners struggle to identify their mistakes and know what to learn next.",
  "cover_flow_3_title": "System",
  "cover_flow_3_desc": "Centering on replay analysis, the system visualizes operational issues and guides players to necessary practice.",
  "cover_flow_4_title": "Architecture",
  "cover_flow_4_desc": "Finally, explain how the game, data collection, AI analysis, multiplayer, and toolchains are integrated.",

  "intro_kicker": "Background: The Competitive Nature of Tetris",
  "intro_h2": "Competitive Tetris requires players to make multiple decisions simultaneously in a short time.",
  "intro_p1": "For many, Tetris is perceived simply as a game of \"arranging falling blocks and clearing full lines.\" However, in competitive Tetris, line clears not only score points but also serve as attacks on the opponent. Players must simultaneously consider the amount of attack they send and how to respond to incoming attacks while managing their own board.",
  "intro_p2": "Furthermore, players utilize NEXT and Hold to predict several steps ahead, choosing elements such as T-Spins, Combos, Back-to-Backs, and canceling depending on the situation. In other words, competitive Tetris is not merely a reflex game, but a real-time task where placement decisions, attacks, defense, and anticipation are compressed into a very short timeframe.",
  "intro_p3": "Therefore, for beginners to improve, simply playing repeatedly is insufficient; it is crucial to review their gameplay afterward to understand which decisions were good and which were problematic. This research focuses precisely on this \"reflection\" process.",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "A mechanism that slightly shifts the block's position during rotation, allowing it to enter gaps it normally could not.",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "A representative technique where a T-block is rotated into a specific slot, generating high attack value from minimal line clears.",
  "intro_fig1": "When attacked, pressure is first displayed in the \"Attack Bar,\" providing an opportunity to cancel it out by clearing one's own lines.",
  "intro_fig2": "If the pressure cannot be handled, the attack converts into \"Garbage Lines\" at the bottom of the field, drastically altering subsequent gameplay.",
  "intro_footnote": "These 1v1 images illustrate the basic mechanics. Attacks do not appear out of nowhere; they are first shown as pressure. If a player cannot cancel it via line clears, the pressure enters the board and becomes \"Garbage Lines\" that must be dealt with.",

  "rules_kicker": "Problem: The Difficulty of Beginner Reflection",
  "rules_h2": "Beginners struggle to understand \"why they lost\" and \"what to improve\" through mere replay playback.",
  "rules_p1": "Existing learning methods include Wikis, video tutorials, and community commentary. While these are effective for learning general knowledge or expert gameplay, they fall short in pinpointing specific misjudgments or mistakes in a player's own matches.",
  "rules_p2": "Moreover, conventional replay functions can play back a match chronologically, but they do not explicitly show the evaluation of each move, its impact on offense/defense, or better alternatives. Thus, even if beginners rewatch the footage, they find it difficult to independently determine \"where they misjudged\" and \"what placement would have been better.\"",
  "rules_p3": "Since factors like board height, holes, attack timing, and canceling decisions interact simultaneously, the root cause of a problem is often not limited to a single move. Therefore, support is required to treat replays not just as video recordings, but as analytical data that visualizes step-by-step decisions.",
  "rules_stack_1_title": "Limits of General Knowledge",
  "rules_stack_1_desc": "Wikis and videos are good for explaining concepts, but fail to indicate which move was problematic in a player's own match.",
  "rules_stack_2_title": "Limits of Conventional Replays",
  "rules_stack_2_desc": "Playback alone rarely indicates step-by-step evaluations or better alternative options.",
  "rules_stack_3_title": "Inefficient Habits",
  "rules_stack_3_desc": "Repetitive practice alone can solidify operations that, while stable, are highly inefficient.",
  "rules_stack_4_title": "Necessary Support",
  "rules_stack_4_desc": "Replays must be treated as analytical data that visualizes decisions, rather than mere video recordings.",
  "rules_demo_wall_title": "Limitations of Traditional Learning",
  "rules_demo_wall_desc": "General commentary can explain \"what to do,\" but cannot automatically point out \"why a specific move was bad in this particular match.\"",
  "rules_demo_tspin_title": "Research Problem Definition",
  "rules_demo_tspin_desc": "For beginners to reflect on their matches and discover mistakes, visualization and analysis based on play data are essential.",

  "source_tetris_title": "Differences in Operation Strategies in Competitive Tetris",
  "source_tetris_desc": "Lindstedt and Gray (2020) frame Tetris as a fast real-time task, demonstrating differences in rotation strategies between novices and experts. This insight suggests that improvement in competitive Tetris is not solely dependent on repetitive practice or reaction speed, but is closely related to decision-making processes accompanied by cognitive load.",

  "origin_kicker": "Proposal: Reflection Support via Replay Analysis",
  "origin_h2": "The objective of this research is to enable beginners to understand their gameplay and discover areas for improvement.",
  "origin_p1": "This research aims to help beginner competitive Tetris players reflect on their matches and understand their mistakes and areas for improvement. To achieve this, a Replay analysis system was developed that records operations, board states, and attack/defense statuses during play, and visualizes step-by-step decisions after the match.",
  "origin_p2": "Therefore, this study treats replays not as simple playback functions, but as data for analyzing the player's own decisions. By linking board states, operation records, and attack/defense situations, the system enables beginners to confirm \"which move became a problem.\"",
  "origin_p3": "Additionally, a Guidebook is provided as prerequisite knowledge to understand the analysis results, allowing players to confirm fundamental techniques like T-Spins and Combos via small simulations. This connects the issues found in the Replay analysis to the player's next practice session.",
  "origin_aside_h3": "Core of the Research",
  "origin_aside_p": "The core of the system is the Replay analysis. The Guidebook is not an independent feature, but a supplementary function to provide the prerequisite knowledge needed to understand the analysis results. AI is also treated not as an end in itself, but as an analytical tool for step-by-step comparison and evaluation.",

  "source_gla_title": "Replay Analysis Based on Game Learning Analytics",
  "source_gla_desc": "Alonso-Fernández et al. (2022) present the Game Learning Analytics framework for collecting, analyzing, and visualizing player interaction data in serious games. Based on this knowledge, this research treats Tetris replay data as a subject of analysis for the learning process.",

  "journey_kicker": "System Overview",
  "journey_h2": "Centering on Replay analysis, the system connects basic understanding, post-match analysis, and improvement practice into a single flow.",
  "journey_step1_h3": "Record Match Data",
  "journey_step1_p": "Saves the board, drop locations, clears, attacks, time, and operation results during play into a format that can be analyzed post-match.",
  "journey_step2_h3": "Visualize Step-by-Step",
  "journey_step2_p": "Displays the board, timeline, attack status, and AI-recommended moves side-by-side in the Replay screen to identify problematic situations.",
  "journey_step3_h3": "Discover Improvements",
  "journey_step3_p": "Compares actual choices with recommended moves to identify terrain degradation, missed attack opportunities, and delayed canceling decisions.",
  "journey_step4_h3": "Supplementary Learning via Guidebook",
  "journey_step4_p": "Allows players to confirm concepts necessary for understanding analysis results, such as T-Spins, Combos, and canceling, through small simulations.",
  "journey_step5_h3": "Confirm Changes",
  "journey_step5_p": "Uses single-match summaries and radar charts to confirm long-term changes in speed, attack, efficiency, and stability.",

  "replay_kicker": "Replay Analysis: Visualizing Step-by-Step Decisions",
  "replay_h2": "The AI does not dictate operations during the match; instead, it analyzes the player's decisions afterward.",
  "replay_p1": "In this system, the AI does not instruct operations during the match, but analyzes the player's choices post-match. This supports post-match reflection without interfering with the player's original decision-making experience.",
  "replay_p2": "In the Replay, players can review the board state, drop locations, line clears, attack volumes, and terrain changes for each move. Rather than just watching the entire match passively, players can trace step-by-step which move led to subsequent disadvantageous situations.",
  "replay_p3": "In the AI evaluation, the player's actual placement is compared with the recommended move obtained through search algorithms. By highlighting moves with significant discrepancies as candidates, the system helps beginners consider \"what they overlooked in this situation.\"",
  "replay_p4": "Furthermore, single-match summaries and radar charts allow players to review speed, attack, efficiency, structure, stability, and vision. This enables the comprehension of not only isolated mistakes but also long-term growth trends.",
  "replay_aside_h3": "Design Principles",
  "replay_aside_p": "The AI does not usurp the player's control, but functions as a post-match coach. The objective is not to \"play on behalf of the player,\" but to \"enable the player to understand their own decisions.\"",
  "replay_fig1_cap": "The Replay interface integrates the board, timeline, AI recommendations, and explanation panels to help players systematically review their choices.",
  "replay_fig2_cap": "Single-match summary data provides an overview of the overall performance in that specific game.",
  "replay_fig3_cap": "The radar chart compresses various ability metrics into an easily comparable shape.",
  "replay_note_h3": "From Single Matches to Long-Term Changes",
  "replay_note_p": "The single-match summary answers \"what happened in this game,\" while the radar chart answers \"what characteristics exist in the ability structure.\" By repeatedly engaging in Replay analysis, players can connect individual experiences into long-term growth.",

  "guide_kicker": "Guidebook: Basic Learning to Understand Analysis Results",
  "guide_h2": "The Guidebook is positioned as supplementary material for understanding Replay analysis.",
  "guide_p1": "For beginners to comprehend the results of Replay analysis, foundational knowledge of T-Spins, Combos, canceling, attack values, and NEXT/Hold usage is essential. Without this knowledge, understanding the meaning behind the AI's recommended moves and evaluations becomes difficult.",
  "guide_p2": "Therefore, the Guidebook divides basic rules and representative techniques into small chapters, allowing confirmation through animations and fixed-scenario simulations. The goal is not merely to increase knowledge, but to understand the issues found in the Replay and bridge them to the next practice session.",
  "guide_p3": "For instance, if a T-Spin opportunity was missed in the Replay, the player can return to the Guidebook's T-Spin chapter to confirm its structure and operation in a fixed scenario. In this way, the Guidebook functions as a supplementary tool supporting a learning cycle centered around Replay analysis.",
  "guide_annotation_title": "Guidebook Screen Composition",
  "guide_annotation_desc": "Integrates the main text, chapter cards, and simulation entrances into a single screen, presenting the learning flow as is.",
  "guide_module_1_title": "Foundational Knowledge",
  "guide_module_1_desc": "Clarifies rules regarding attack power, garbage lines, canceling, B2B, and Combos.",
  "guide_module_2_title": "Operation Section",
  "guide_module_2_desc": "Divides techniques like Wall Kicks, Combos, and T-Spin Doubles into small, learnable chapters.",
  "guide_module_3_title": "Simulation Exercises",
  "guide_module_3_desc": "Transitions the player to a fixed scenario to successfully complete a target action once using actual inputs.",
  "guide_module_4_title": "Feedback",
  "guide_module_4_desc": "The system determines whether the goal was achieved, notifying the player if the action was correctly executed.",

  "arch_kicker": "Implementation: Recording, Evaluating, and Visualizing Play Data",
  "arch_h2": "To realize Replay analysis, the state of each move is recorded, evaluated, and visualized on the screen.",
  "arch_title_entry": "Data Required for Analysis",
  "arch_entry_1": "Board Snapshot",
  "arch_entry_2": "Inputs and Drops",
  "arch_entry_3": "Clears, Attacks, Cancels",
  "arch_entry_4": "Speed and Steps",
  "arch_connector": "Data recorded during the match is reconstructed post-match in the Replay screen, and utilized for AI evaluation and visualization.",
  "arch_layer_1_title": "Game Execution Layer",
  "arch_layer_1_i1": "10 × 20 Board",
  "arch_layer_1_i2": "SRS Rotation and Wall Kicks",
  "arch_layer_1_i4": "Combo / B2B / T-Spin Judgments",
  "arch_layer_2_title": "Data Collection Layer",
  "arch_layer_2_i1": "Drop Locations per Move",
  "arch_layer_2_i2": "Board Snapshots",
  "arch_layer_2_i3": "Line Clears and Attacks",
  "arch_layer_2_i4": "Time, Speed, and Results",
  "arch_layer_3_title": "Analysis & Visualization Layer",
  "arch_layer_3_i1": "Comparison with AI Moves",
  "arch_layer_3_i2": "Timeline Display",
  "arch_layer_3_i3": "Single Match Summaries",
  "arch_layer_3_i4": "Radar Charts",
  "arch_flow_1_title": "Match Data",
  "arch_flow_1_desc": "Step-by-step records generated during actual gameplay.",
  "arch_flow_2_title": "Analysis Algorithm",
  "arch_flow_2_desc": "Searches candidate routes and scores them using evaluation functions.",
  "arch_flow_3_title": "Replay Visualization",
  "arch_flow_3_desc": "Timelines, recommended drops, data panels, and radar charts.",
  "arch_support_title": "Implementation Notes",
  "arch_support_1_title": "Tri-lingual Localization",
  "arch_support_1_desc": "Chinese / Japanese / English",
  "arch_support_2_title": "Input Support",
  "arch_support_2_desc": "Keyboard and Controller",
  "arch_support_3_title": "Assets and UI",
  "arch_support_3_desc": "Lobby, Board, Replay Screen",
  "arch_support_4_title": "Online Multiplayer",
  "arch_support_4_desc": "Online battle data is also being collected.",

  "tech_kicker": "Future Work: Evaluation Experiments and Enhancing Analysis Accuracy",
  "tech_h2": "Moving forward, it is necessary to verify whether this system effectively supports beginners' reflection.",
  "tech_p1": "At this stage, the mechanisms and visualization interfaces for Replay analysis have been implemented. The next challenge is to evaluate whether beginners can more easily comprehend their mistakes and areas for improvement by using this system.",
  "tech_p2": "As an evaluation method, it is necessary to verify whether players can explain their mistakes, understand the meaning of recommended moves, and reduce the occurrence of similar errors before and after using the system. By combining questionnaires with simple gameplay tasks, the system's effectiveness as a learning support tool can be validated.",
  "tech_p3": "Additionally, there is room for improvement in the accuracy of AI evaluations. The current evaluation function scores routes based on metrics like board height, holes, and attack opportunities; however, to convert these into explanations that are easy for beginners to understand, the reasons for evaluation must be presented more clearly.",
  "tech_p4": "Furthermore, while the online multiplayer feature is not the main subject at present, it is positioned as an expansion feature for collecting diverse gameplay data and broadening the scope of analysis in the future. This research currently narrows its focus to reflection support for beginners via Replay analysis.",
  "tech_card_1_title": "Evaluation Experiments",
  "tech_card_1_desc": "Confirm whether beginners can more easily explain their mistakes and improvements.",
  "tech_card_2_title": "Analysis Accuracy",
  "tech_card_2_desc": "Verify whether recommended moves and evaluation functions genuinely aid beginners' improvement.",
  "tech_card_3_title": "Explainability",
  "tech_card_3_desc": "Explain why a specific move is better using board metrics and natural language.",
  "tech_card_4_title": "Guidebook Integration",
  "tech_card_4_desc": "Naturally connect analysis results to relevant foundational chapters.",
  "tech_card_5_title": "Online Data",
  "tech_card_5_desc": "Utilize collected online battle data for evaluation and analysis.",

  "closing_label": "Conclusion",
  "closing_h2": "The core of this research is Replay analysis support, aimed at enabling beginners to understand their gameplay and discover areas for improvement.",
  "closing_p": "Traditionally, even when beginners reviewed conventional replays, they faced the challenge of struggling to understand exactly which decisions were problematic. Therefore, this research developed a Replay analysis system that records board, operation, and attack statuses, and visualizes step-by-step decisions post-match. The Guidebook and AI evaluations are positioned as supplementary elements to support this central objective."
};

const appjsPath = path.join(__dirname, 'app.js');
let content = fs.readFileSync(appjsPath, 'utf-8');

// Find the index of the first `const progress = document.querySelector("#scrollProgress");`
const logicStartIndex = content.indexOf('const progress = document.querySelector("#scrollProgress");');

const newTranslationsStr = `const translations = {
  "zh-CN": ${JSON.stringify(zh, null, 2)},
  "ja": ${JSON.stringify(ja, null, 2)},
  "en": ${JSON.stringify(en, null, 2)}
};

`;

const finalContent = newTranslationsStr + content.slice(logicStartIndex);
fs.writeFileSync(appjsPath, finalContent, 'utf-8');
console.log('Successfully regenerated app.js');
