const translations = {
  "zh-CN": {
    "page_title": "俄罗斯方块学习与复盘系统 | 中文核心文档",
    "nav_foreword": "前言",
    "nav_intro": "引言",
    "nav_origin": "起因",
    "nav_rules": "对战规则",
    "nav_journey": "玩家路径",
    "nav_guidebook": "Guidebook",
    "nav_replay": "Replay",
    "nav_architecture": "架构",
    "nav_tech": "技术",
    "brand_title": "俄罗斯方块学习系统",
    "cover_author": "by wanheng",
    "cover_github": "GitHub",
    "cover_download": "下载",
    "cover_label": "中文核心文档",
    "cover_h1": "从俄罗斯方块的竞技性出发，设计一个帮助玩家变强的学习与复盘系统。",
    "cover_lead": "俄罗斯方块并不只是把方块排满一行再消掉。在对战中，玩家需要兼顾进攻与防守、提前规划落点、在高速下做出判断，还要通过赛后复盘不断修正自己的打法——这些要素共同构成了一套持续对抗的竞技体系。这个项目围绕“玩家如何从入门走向进阶”展开，重点讨论学习系统、复盘分析与整体技术结构。",
    "cover_flow_1_title": "前言",
    "cover_flow_1_desc": "先用普通语言说明俄罗斯方块为什么具有竞技性。",
    "cover_flow_2_title": "起因",
    "cover_flow_2_desc": "玩家想提升水平、击败更强对手，却缺少足够好用的辅助工具。",
    "cover_flow_3_title": "设计",
    "cover_flow_3_desc": "通过 Guidebook 与 Replay，分别解决“怎么学”和“哪里错”。",
    "cover_flow_4_title": "结构",
    "cover_flow_4_desc": "最后说明游戏、数据采集、AI 分析、多人对战和工具链如何组合。",
    "intro_kicker": "引言：先理解俄罗斯方块",
    "intro_h2": "俄罗斯方块不只是“把方块排满一行再消掉”。",
    "intro_p1": "很多人第一次想到俄罗斯方块时，脑中出现的是一个很简单的画面：方块从上往下落，玩家把它们排整齐，凑满一行就消掉。如果只看这一层，它确实像一个单人益智游戏。但俄罗斯方块，尤其是对战型俄罗斯方块，已经发展成了很接近电子竞技的系统。",
    "intro_p2": "在对战中，玩家并不是单纯追求“活得久”。每一次消行都可能转化成对对手的攻击。对手收到攻击后，棋盘下方会出现垃圾行，场地被不断向上推高。谁能更快地制造压力，谁能更稳定地处理压力，谁就更接近胜利。",
    "intro_p3": "正因如此，认真打俄罗斯方块和训练一项竞技项目并没有本质区别。玩家不仅要练操作速度，还要理解攻击效率、堆叠结构、预览判断、Hold 的使用、T-Spin、Combo、Back-to-Back 等概念。这些要素相互交织，形成了一套既有学习曲线、也有策略深度，同时值得反复复盘的竞技体系。",
    "intro_aside_h3": "面向完全不了解俄罗斯方块的读者",
    "intro_aside_p": "对战俄罗斯方块的重点不只是消行，而是把消行转化为压力，再把压力施加给对手。玩家既要制造攻击，也要处理自己收到的攻击。",
    "intro_fig1": "受到攻击时，压力会先显示在攻击条中，玩家还有机会通过自己的消行去抵消。",
    "intro_fig2": "如果压力没有被处理，攻击会转化为棋盘底部的垃圾行，直接改变接下来的局面。",
    "intro_footnote": "这两张 1v1 图展示了基本机制：攻击不会凭空出现，它先作为压力显示出来；如果玩家没有通过自己的消行抵消，压力就会进入棋盘，变成必须处理的垃圾行。",
    "origin_kicker": "项目起因",
    "origin_h2": "理解了这些之后，想变强的玩家会发现：趁手的学习工具几乎没有。",
    "origin_p1": "玩家接触俄罗斯方块后，很快会产生一个自然目标：不仅要能稳定生存，还要能在对战中击败更多、更强的对手。这个目标会推动玩家继续学习攻击方式、堆叠方法、T-Spin、Combo，以及如何在压力下保持局面稳定。",
    "origin_p2": "现有资料中确实存在俄罗斯方块百科、视频教程和社区讨论，但这些内容通常更像资料库。它们能解释概念，却不一定能让玩家马上进入一个固定局面亲自尝试；也能展示高手操作，却不一定能指出普通玩家在自己对局中具体哪一步出现问题。",
    "origin_p3": "因此，系统设计的起点不是再增加一个普通模式，而是补上两类学习工具：一个负责把知识和操作连接起来，一个负责把玩家自己的对局拆开分析。前者是 Guidebook，后者是 Replay。",
    "origin_aside_h3": "设计起点",
    "origin_aside_p": "玩家真正需要的是可操作的学习环境和可回看的错误分析。只阅读概念不够，只反复游玩也不一定能发现问题。",
    "rules_kicker": "对战规则的最小解释",
    "rules_h2": "要理解它的竞技深度，先要知道一件事：消行就是攻击。",
    "rules_p1": "在普通印象里，消一行只是得分。但在对战俄罗斯方块里，消行同时也是一种攻击行为。消得越有价值，给对手制造的压力越大。例如一次消四行，也就是 Tetris，通常比零散地消一两行更有攻击价值。",
    "rules_p2": "更进一步，T-Spin Double 这类技巧虽然只消两行，却因为操作难度和结构要求更高，在很多现代规则中能产生接近甚至等同于 Tetris 的攻击力。这就是为什么进阶玩家会主动学习 T-Spin：它不是炫技，而是更高效率地把有限方块转化为攻击。",
    "rules_p3": "同时，玩家还可以看到接下来 5 个方块，并可以把一个方块暂存在 Hold 中。这让俄罗斯方块不再只是反应游戏，也像棋类游戏一样，需要提前规划几步之后的局面。",
    "rules_stack_1_title": "棋盘",
    "rules_stack_1_desc": "标准场地是 10 列 × 20 行。越接近顶部，死亡风险越高。",
    "rules_stack_2_title": "Next 5 + Hold",
    "rules_stack_2_desc": "玩家能看到后续 5 个方块，并能暂存 1 个方块，因此每一步都带有规划性质。",
    "rules_stack_3_title": "攻击与垃圾行",
    "rules_stack_3_desc": "高价值消行会给对手发送垃圾行。垃圾行会抬高场地，压缩可操作空间。",
    "rules_stack_4_title": "抵消",
    "rules_stack_4_desc": "自己即将受到攻击时，可以通过消行抵消部分压力，而不是只能被动承受。",
    "rules_demo_wall_title": "Wall Kick",
    "rules_demo_wall_desc": "方块旋转时撞到墙壁，系统会尝试偏移位置，从而让 L 方块插入空隙。",
    "rules_demo_tspin_title": "T-Spin",
    "rules_demo_tspin_desc": "T 方块通过旋转进入槽位，并同时消除 2 行。",
    "source_tetris_title": "Tetris 中高手与新手的策略差异",
    "source_tetris_desc": "Lindstedt and Gray（2020）将 Tetris 定位为高速实时任务，并指出初学者与熟练者在旋转操作策略上存在差异。这说明对战型 Tetris 的进步不仅依赖反复练习或反应速度，也与带有认知负荷的判断过程有关。",
    "source_gla_title": "游戏内行为数据的收集、分析与可视化",
    "source_gla_desc": "Alonso-Fernández et al.（2022）提出了在 serious games 中收集、分析、可视化玩家交互数据的 Game Learning Analytics 框架。本研究基于这一方法，将 Tetris replay 数据作为学习过程的分析对象。",
    "journey_kicker": "从玩家需求逆推系统",
    "journey_h2": "所以我们先问了一个问题：玩家到底是怎样一步步变强的？",
    "journey_step1_h3": "首先，玩家需要知道自己在玩什么。",
    "journey_step1_p": "新手最先需要的不是复杂技巧，而是基础知识：棋盘结构、方块种类、Hold、Next、消行、攻击、垃圾行，以及为什么有些消除方式更有价值。",
    "journey_step2_h3": "然后，玩家需要一个人安全地练习。",
    "journey_step2_p": "单人 Marathon 模式承担这个任务。玩家可以不被对手干扰，先熟悉操作、堆叠、消行节奏和游戏速度。这个阶段解决的是“能不能稳定玩下去”。",
    "journey_step3_h3": "接着，玩家会开始思考怎样才能打得更好。",
    "journey_step3_p": "这时需要 Guidebook。它负责解释 Wall Kick、Combo、T-Spin 等技巧背后的原理，并通过模拟演练让玩家在预设棋盘中实际操作一次。",
    "journey_step4_h3": "再往后，玩家会想知道自己哪里错了。",
    "journey_step4_p": "单纯多玩可能重复同样的问题。Replay 系统将对局拆解，帮助玩家快速发现低质量操作，并通过 AI 推荐路线指导后续练习。",
    "journey_step5_h3": "最后，玩家需要确认自己的进步。",
    "journey_step5_p": "玩家可以通过长期数据、雷达图和对战结果确认成长。进步有时很小，体感不明显，但数据可以把这种变化留下来。",
    "guide_kicker": "Guidebook：从“知道概念”到“亲手做过”",
    "guide_h2": "第一步，解决“怎么学”：让玩家不只是看教程，而是亲手做一次。",
    "guide_p1": "很多玩家看过 T-Spin 或 Combo 的视频，但真正回到游戏里时，仍然不知道该怎样构造局面。原因很简单：俄罗斯方块的技巧不是只靠“看懂”就能掌握的，玩家必须在真实棋盘上完成移动、旋转、下落和消除，才能理解这个技巧为什么成立。",
    "guide_p2": "所以 Guidebook 的设计不是传统说明书，而是一个学习入口。它先用普通语言解释技巧，再给出必要的背景知识和操作顺序，最后让玩家进入模拟演练。在模拟演练里，棋盘、当前方块、目标和成功条件都是固定的，玩家只需要聚焦在这一个知识点上。",
    "guide_p3": "这样做的目的，是把学习压力拆小。玩家不需要在完整对局里碰运气等到合适局面，也不需要一边被对手攻击一边学习新技巧。他可以在一个可控场景中，先把核心动作做对一次。",
    "guide_module_1_title": "基础知识",
    "guide_module_1_desc": "攻击力、垃圾行、抵消、B2B、Combo 等规则先讲清楚。",
    "guide_module_2_title": "操作章节",
    "guide_module_2_desc": "Wall Kick、Combo、T-Spin Double 等内容拆成可学习的小章节。",
    "guide_module_3_title": "模拟演练",
    "guide_module_3_desc": "玩家进入固定局面，用真实操作完成一次目标动作。",
    "guide_module_4_title": "反馈",
    "guide_module_4_desc": "系统判断是否完成目标，让玩家知道动作是否真正成立。",
    "guide_annotation_title": "Guidebook 页面示例",
    "guide_annotation_desc": "这张注释图展示了章节说明、知识卡片和模拟入口如何组合在同一页，让读者能直接看到学习流程。",
    "replay_kicker": "Replay：把“感觉打得还行”变成可观察的数据",
    "replay_h2": "第二步，解决“哪里错”：AI 在赛后帮你复盘，而不是在赛中替你操作。",
    "replay_p1": "如果 AI 在对局中不断提示玩家应该怎么放，短期看起来很方便，但它可能会干扰玩家自己的判断。玩家会变成跟随提示操作，而不是建立自己的局面理解。俄罗斯方块的核心乐趣之一，正是玩家在压力中独立做出选择。",
    "replay_p2": "因此，AI 的主要作用被放在对局之后。玩家先完整打一局，保留原本的游戏体验；结束后再进入 Replay，像看比赛录像一样查看自己每一步的选择。这样 AI 不替玩家玩，而是在游戏外帮助玩家理解自己。",
    "replay_p3": "Replay 首先给出逐步评分。玩家可以快速定位一局中损失较大的操作。找到问题后，玩家自然会问：那这一步有没有更好的放法？于是系统显示 AI 推荐的下落位置，并给出接下来数步的路线参考。它不是一句抽象建议，而是直接把“更好的选择”放到棋盘上。",
    "replay_p4": "另一方面，玩家也需要知道整局表现如何。左侧数据面板统计一局的整体表现，雷达图则把速度、攻击、效率、结构、稳定性、视野等维度可视化。当玩家一段时间后再次比较这些数据，就能看到自己一点点变强的证据。",
    "replay_aside_h3": "Replay 的设计原则",
    "replay_aside_p": "AI 不应该抢走玩家的操作权。它更像赛后的教练：先让玩家完成比赛，再指出问题、展示参考答案，并把进步记录下来。",
    "replay_fig1_cap": "Replay 界面把棋盘、时间线、AI 推荐和解释面板放在一起，帮助玩家逐步检查自己的选择。",
    "replay_fig2_cap": "单局概要数据让玩家知道这一局整体表现如何。",
    "replay_fig3_cap": "雷达图把不同能力维度压缩成一个容易比较的形状。",
    "replay_note_h3": "从一局到长期变化",
    "replay_note_p": "单局概要回答“这一局发生了什么”，雷达图回答“能力结构有什么特点”。当玩家反复复盘，就能把每一局的经验连接成长期进步。",
    "arch_kicker": "项目结构",
    "arch_h2": "这些模块不是各做各的，而是围绕玩家成长串成一条完整的链路。",
    "arch_title_entry": "大厅入口",
    "arch_entry_1": "单人练习",
    "arch_entry_2": "知识与模拟演练",
    "arch_entry_3": "赛后分析",
    "arch_entry_4": "1v1 / 多人对战",
    "arch_connector": "玩家在不同模式之间循环：练习 → 学习 → 复盘 → 对战 → 再练习",
    "arch_layer_1_title": "游戏运行层",
    "arch_layer_1_i1": "10 × 20 棋盘",
    "arch_layer_1_i2": "SRS 旋转与 Wall Kick",
    "arch_layer_1_i4": "Combo / B2B / T-Spin 判定",
    "arch_layer_2_title": "数据采集层",
    "arch_layer_2_i1": "每一步落点",
    "arch_layer_2_i2": "棋盘快照",
    "arch_layer_2_i3": "消行与攻击",
    "arch_layer_2_i4": "时间、速度与操作结果",
    "arch_layer_3_title": "多人同步层",
    "arch_layer_3_i1": "WebSocket 服务器",
    "arch_layer_3_i2": "房间与玩家状态",
    "arch_layer_3_i3": "攻击发送与接收",
    "arch_layer_3_i4": "1v1 / 多人模式扩展",
    "arch_flow_1_title": "对局数据",
    "arch_flow_1_desc": "玩家真实游玩产生的逐步记录",
    "arch_flow_2_title": "分析算法",
    "arch_flow_2_desc": "搜索候选路线并用评价函数打分",
    "arch_flow_3_title": "Replay 可视化",
    "arch_flow_3_desc": "时间线、推荐落点、数据面板、雷达图",
    "arch_support_title": "支撑系统",
    "arch_support_1_title": "三语本地化",
    "arch_support_1_desc": "中 / 日 / 英",
    "arch_support_2_title": "输入适配",
    "arch_support_2_desc": "键盘与手柄",
    "arch_support_3_title": "素材与 UI",
    "arch_support_3_desc": "大厅、棋盘、复盘界面",
    "arch_support_4_title": "开发工具链",
    "arch_support_4_desc": "Agent / MCP / CLI",
    "tech_kicker": "技术解释",
    "tech_h2": "最后聊一下技术：这里的 AI 不靠大模型，靠的是搜索与评价。",
    "tech_p1": "俄罗斯方块的 AI 分析更接近棋类游戏。原因是玩家并不是完全盲目地接收方块：现代规则中，玩家可以看到接下来的 5 个方块，还可以通过 Hold 保存一个方块。也就是说，系统可以在一定范围内预测接下来的局面，并搜索不同放法带来的结果。",
    "tech_p2": "因此，这里的 AI 核心并不需要 CNN、RNN，也不需要 LLM。它更像 AlphaGo 时代的思路：先生成候选操作，再向后搜索几步，最后用评价函数判断局面质量。评价函数会把 10 × 20 棋盘上的情况拆成许多指标，例如高度、空洞、表面凹凸、攻击机会、未来可持续性等。",
    "tech_p3": "当 Replay 分析某一步时，算法会比较玩家实际选择和搜索得到的推荐选择。如果两者差距很大，系统就能标出这一步可能是问题操作。这样，AI 的作用不是给出一句模糊评价，而是把“这个局面下更好的路线”计算出来，再通过界面展示给玩家。",
    "tech_p4": "项目本体基于 Godot 开发。Godot 是一个开源游戏引擎，定位上类似 Unity，但更轻量，适合快速制作 2D/3D 游戏原型并持续迭代。配合 Agent、MCP、CLI 化工具，小型项目可以更快地修改 UI、调试流程、整理文档和扩展工具链。",
    "tech_card_1_title": "Godot",
    "tech_card_1_desc": "负责游戏画面、UI、输入、场景和主要玩法逻辑。",
    "tech_card_2_title": "搜索算法",
    "tech_card_2_desc": "围绕 Next 5 与 Hold 搜索未来几步的候选路线。",
    "tech_card_3_title": "评价函数",
    "tech_card_3_desc": "把棋盘结构拆成多项指标，对每条路线进行打分。",
    "tech_card_4_title": "WebSocket",
    "tech_card_4_desc": "用于在线对战中的房间、同步和攻击传递。",
    "tech_card_5_title": "开发工具链",
    "tech_card_5_desc": "Agent / MCP / CLI 帮助快速完成修改、检查和文档化。",
    "closing_label": "结语",
    "closing_h2": "系统的重点，是把“玩家想变强”这件事拆成可以学习、可以操作、可以复盘、也可以验证的过程。",
    "closing_p": "Guidebook 解决“应该学什么、怎么亲手做一次”的问题；Replay 解决“哪里做得不好、有没有更好选择”的问题；多人对战则提供最终的验证环境。整个项目不是单个功能的集合，而是一条围绕玩家成长逆向设计出来的路径。"
  },
  "ja": {
    "page_title": "テトリス学習とリプレイシステム | コア・ドキュメント",
    "nav_foreword": "はじめに",
    "nav_intro": "イントロダクション",
    "nav_origin": "きっかけ",
    "nav_rules": "対戦ルール",
    "nav_journey": "プレイヤーの道のり",
    "nav_guidebook": "Guidebook",
    "nav_replay": "Replay",
    "nav_architecture": "アーキテクチャ",
    "nav_tech": "テクノロジー",
    "brand_title": "テトリス学習システム",
    "cover_author": "by WANHENG（バンコウ）",
    "cover_github": "GitHub",
    "cover_download": "ダウンロード",
    "cover_label": "コア・ドキュメント",
    "cover_h1": "対戦型テトリス初心者の振り返りを支援するリプレイ分析システム",
    "cover_lead": "対戦型テトリスでは、プレイヤーは高速な時間制約の中で、落下位置、回転、攻撃、防御を判断し続ける必要があります。しかし初心者は、自分の操作のどこに問題があったのかを試合後に把握しにくく、反復練習だけでは低効率な操作習慣を固定してしまう可能性があります。そこで本研究では、リプレイデータを用いて操作と判断を可視化し、必要に応じてガイドブック型の練習へ接続する学習支援システムを開発しました。",
    "cover_flow_1_title": "はじめに",
    "cover_flow_1_desc": "まず、テトリスがなぜ競技性を持っているのかを分かりやすい言葉で説明します。",
    "cover_flow_2_title": "問題",
    "cover_flow_2_desc": "高速な判断と操作戦略が必要である一方、初心者は自分のミスや次に学ぶべき内容を把握しにくい。",
    "cover_flow_3_title": "システム",
    "cover_flow_3_desc": "リプレイ分析を中心に、操作の問題を可視化し、必要な練習へ導く学習支援を行います。",
    "cover_flow_4_title": "システム構造",
    "cover_flow_4_desc": "最後に、ゲーム、データ収集、AI分析、マルチプレイ対戦、そしてツールチェーンがどのように組み合わされているかを説明します。",
    "intro_kicker": "イントロダクション：まずテトリスを理解する",
    "intro_h2": "イントロダクション：テトリスは単に「ブロックを並べて消す」だけではありません。",
    "intro_p1": "多くの人がテトリスを思い浮かべるとき、ブロックが上から落ちてきて、それをきれいに並べて一列揃えて消す、というシンプルな画面を想像するでしょう。その側面だけを見れば、確かに1人用のパズルゲームです。しかし、テトリス、特に対戦型テトリスは、eスポーツに非常に近いシステムへと進化しています。",
    "intro_p2": "対戦では、単に「長く生き残る」ことだけを目指すわけではありません。ラインを消すたびに、それが相手への攻撃へと変換される可能性があります。攻撃を受けると、フィールドの底に「お邪魔ブロック（Garbage Lines）」が現れ、盤面がどんどん上に押し上げられます。いかに早くプレッシャーを与え、いかに安定してプレッシャーを処理できるかが、勝利へのカギとなります。",
    "intro_p3": "だからこそ、テトリスに真剣に取り組むことは、一つの競技種目をトレーニングすることと本質的に変わりません。操作スピードを鍛えるだけでなく、攻撃効率、積み方の構造、NEXT（次に来るブロック）の判断、Hold の使い方、T-Spin、Combo、Back-to-Back といった概念を理解する必要があります。これらの要素が互いに絡み合い、学習曲線と戦略的な深みを持ち、繰り返し振り返る価値のある競技システムを形作っています。",
    "intro_aside_h3": "テトリスを全く知らない方へ",
    "intro_aside_p": "対戦テトリスで重要なのは、ただラインを消すことではなく、それを「プレッシャー（攻撃）」に変換し、相手に送り込むことです。プレイヤーは攻撃を作り出すと同時に、受けた攻撃を処理しなければなりません。",
    "intro_fig1": "攻撃を受けると、プレッシャーはまず「アタックゲージ（攻撃バー）」に表示され、自身のライン消去によって相殺（相殺）するチャンスがあります。",
    "intro_fig2": "プレッシャーを処理できなかった場合、攻撃はフィールドの底の「お邪魔ブロック」に変わり、その後の展開を大きく変えてしまいます。",
    "intro_footnote": "これらの 1v1 の画像は基本的なメカニクスを示しています。攻撃は突然現れるのではなく、まずプレッシャーとして表示されます。自分のライン消去で相殺できなければ、そのプレッシャーは盤面に入り込み、処理しなければならない「お邪魔ブロック」になります。",
    "origin_kicker": "研究背景：従来の問題",
    "origin_h2": "従来は、対戦型テトリス初心者が自分の判断や操作の問題を把握しにくいという課題がありました。",
    "origin_p1": "対戦型テトリスでは、単にラインを消すだけでなく、攻撃を作る判断、相手からの攻撃を処理する防御、T-Spin や Combo のような高価値な技術を組み合わせる必要があります。初心者にとって、このような判断を試合中に行い、さらに試合後に自分の問題点を言語化することは簡単ではありません。",
    "origin_p2": "Lindstedt and Gray（2020）は、テトリスを高速なリアルタイム課題として扱い、初心者・地域大会レベル・世界大会レベルのプレイヤーの回転操作戦略を比較しています。この研究では、熟練者ほど効率的な両方向回転戦略を用いる一方、その戦略には判断時間という認知的コストも伴うことが示されています。",
    "origin_p3": "また、Alonso-Fernández et al.（2022）は、Game Learning Analytics を、ゲーム内のプレイヤー行動を収集・分析・可視化し、学習者の行動や戦略を理解するための方法として説明しています。これらの先行研究から、テトリスの上達支援においても、プレイヤーのリプレイデータを可視化し、操作や判断の改善点を示すことが重要であると考えられます。",
    "origin_aside_h3": "そこで本研究では",
    "origin_aside_p": "対戦型テトリス初心者のリプレイデータを分析し、どの操作や判断が問題になったのかを盤面上で可視化するシステムを開発しました。Guidebook は独立した機能ではなく、リプレイ分析で見つかった課題を練習へつなげる補助機能として位置づけます。",
    "rules_kicker": "対戦ルールの最小限の解説",
    "rules_h2": "対戦ルール：ライン消去は、攻撃でもあります。",
    "rules_p1": "一般的なイメージでは、ラインを消すことは単なるスコア獲得です。しかし、対戦テトリスでは、ライン消去は同時に「攻撃行動」でもあります。価値の高い消し方をするほど、相手に大きなプレッシャーを与えられます。例えば、一度に4ラインを消すこと（Tetris）は、通常、バラバラに1～2ラインを消すよりも高い攻撃力（攻撃価値）を持ちます。",
    "rules_p2": "さらに一歩進んで、T-Spin Double のようなテクニックは2ラインしか消しませんが、操作の難易度と構造の要求が高いため、多くのルールでは Tetris に近い、あるいは同等の攻撃力を生み出します。これこそが、上級プレイヤーが自発的に T-Spin を学ぶ理由です。それは単なる魅せプレイではなく、限られたブロックをより高い効率で攻撃に変換するための手段なのです。",
    "rules_p3": "同時に、プレイヤーは次に来る5つのブロック（NEXT）を見ることができ、1つのブロックを Hold に一時保存（ホールド）することができます。これにより、テトリスは単なる反射神経のゲームではなくなり、チェスや将棋のように数手先の盤面を計画することが求められます。",
    "rules_stack_1_title": "盤面（フィールド）",
    "rules_stack_1_desc": "標準的なフィールドは 幅10マス × 高さ20マス です。頂上に近づくほど、ゲームオーバーのリスクが高まります。",
    "rules_stack_2_title": "Next 5 + Hold",
    "rules_stack_2_desc": "今後の5つのブロックを確認でき、1つを保存できるため、毎手ごとに計画的な要素が伴います。",
    "rules_stack_3_title": "攻撃とお邪魔ブロック（Garbage Lines）",
    "rules_stack_3_desc": "価値の高いライン消去は相手にお邪魔ブロックを送ります。これが盤面を押し上げ、操作可能なスペースを圧迫します。",
    "rules_stack_4_title": "相殺",
    "rules_stack_4_desc": "自分が攻撃を受けそうな時、ただ受動的に耐えるのではなく、自身のライン消去でプレッシャーの一部を打ち消すことができます。",
    "rules_demo_wall_title": "Wall Kick",
    "rules_demo_wall_desc": "回転が壁に当たった時、システムが位置をずらし、L ブロックを隙間へ入れられるようにします。",
    "rules_demo_tspin_title": "T-Spin",
    "rules_demo_tspin_desc": "T ブロックを回転で入れ、同時に2ラインを消します。",
    "source_tetris_title": "Tetris における熟練者と初心者の戦略差",
    "source_tetris_desc": "世界大会レベルのプレイヤーは余分な回転入力を減らす一方、複雑な判断により初期反応時間が長くなる場面もある。Tetris が単純な反射ゲームではなく、認知負荷を伴うリアルタイム課題である根拠として用いる。",
    "source_gla_title": "ゲーム内行動データの収集・分析・可視化",
    "source_gla_desc": "Alonso-Fernández et al.（2022）は，シリアスゲームにおけるプレイヤーのインタラクションデータを収集・分析・可視化する Game Learning Analytics の枠組みを示している。本研究では，この知見に基づき，テトリスのリプレイデータを学習過程の分析対象として扱う。",
    "journey_kicker": "プレイヤーのニーズからのシステム逆算",
    "journey_h2": "プレイヤーの道のり：どうやって少しずつ強くなるのか。",
    "journey_step1_h3": "まず、自分が何をプレイしているのかを知る。",
    "journey_step1_p": "初心者が最初に必要とするのは複雑なテクニックではなく、基礎知識です。盤面の構造、ブロックの種類、Hold、Next、ライン消去、攻撃、お邪魔ブロック、そしてなぜ特定の消し方により高い価値があるのかを学びます。",
    "journey_step2_h3": "次に、一人で安全に練習できる場所を求める。",
    "journey_step2_p": "ソロの Marathon（マラソン）モードがこの役割を担います。相手に邪魔されることなく、操作、積み方、ライン消去のリズム、ゲームスピードに慣れることができます。この段階の目標は「安定してプレイし続けられるか」です。",
    "journey_step3_h3": "そして、どうすればもっと上手くプレイできるか考え始める。",
    "journey_step3_p": "ここで Guidebook の出番です。Wall Kick、Combo、T-Spin といったテクニックの背後にある原理を説明し、あらかじめ設定された盤面での「シミュレーション演習」を通じて、プレイヤーに実際に一度操作してもらいます。",
    "journey_step4_h3": "さらに進むと、自分のどこが間違っていたのかを知りたくなる。",
    "journey_step4_p": "ただプレイするだけでは同じミスを繰り返すかもしれません。Replay システムは対局を分解し、AIの推奨ルートを通じて弱点を素早く発見し、練習に活かすことができます。",
    "journey_step5_h3": "最後に、自身の成長を確認したいと願う。",
    "journey_step5_p": "長期的なデータ、レーダーチャート、対戦結果などを通じて自身の成長を確認できます。進歩は非常に小さく、体感しにくいこともありますが、データはその変化を記録として残してくれます。",
    "guide_kicker": "Guidebook：「概念を知る」から「実際にやってみる」へ",
    "guide_h2": "Guidebook：「どう学ぶか」を解決し、実際に手を動かしてもらう。",
    "guide_p1": "T-Spin や Combo の動画を見た多くのプレイヤーも、実際にゲームに戻ると、どうやってその局面を作ればいいのか分からないことがよくあります。理由は簡単です。テトリスのテクニックは「見て理解する」だけでマスターできるものではなく、実際の盤面で移動、回転、落下、消去を自分で行ってはじめて、そのテクニックが成立する理由を理解できるからです。",
    "guide_p2": "そのため、Guidebook は従来のマニュアルではなく、学習のエントランスとしてデザインされています。まずテクニックを分かりやすい言葉で解説し、必要な前提知識と操作手順を示してから、シミュレーション演習へと導きます。シミュレーション演習では、盤面、現在のブロック、目標、成功条件がすべて固定されており、プレイヤーはその1つの知識ポイントにだけ集中することができます。",
    "guide_p3": "この目的は、学習のプレッシャーを小さく分割することです。プレイヤーは、実際の対局で都合の良い局面が運良く訪れるのを待つ必要も、相手に攻撃されながら新しいテクニックを学ぶ必要もありません。コントロールされた状況の中で、まずはコアとなるアクションを正しく一度実行できるのです。",
    "guide_module_1_title": "基礎知識",
    "guide_module_1_desc": "攻撃力、お邪魔ブロック、相殺、B2B、Combo などのルールを明確にします。",
    "guide_module_2_title": "操作セクション",
    "guide_module_2_desc": "Wall Kick、Combo、T-Spin Double などを学習可能な小さな章に分割します。",
    "guide_module_3_title": "シミュレーション演習",
    "guide_module_3_desc": "プレイヤーは固定された局面に移行し、実際の操作で目標アクションを1度完了させます。",
    "guide_module_4_title": "フィードバック",
    "guide_module_4_desc": "システムが目標達成を判定し、アクションが正しく成立したかをプレイヤーに知らせます。",
    "guide_annotation_title": "Guidebook 画面の例",
    "guide_annotation_desc": "この注釈付き画像は、章の説明、知識カード、シミュレーション入口が同じページでどう組み合わさるかを示しています。",
    "replay_kicker": "Replay：「そこそこ上手くできた」を観察可能なデータに変える",
    "replay_h2": "Replay：「どこが間違っていたか」を試合後に振り返る。",
    "replay_p1": "もしAIが対局中に「どこに置くべきか」を絶えず指示してきたら、短期的には便利に見えるかもしれませんが、プレイヤー自身の判断を妨げる恐れがあります。プレイヤーは盤面の理解を構築するのではなく、指示に従うだけの操作になってしまいます。プレッシャーの中で自立して選択をすることこそが、テトリスの核心的な楽しみの一つです。",
    "replay_p2": "そのため、AIの主な役割は対局後に置かれています。プレイヤーはまず本来のゲーム体験を損なうことなく1ゲームを完走します。終了後、Replay に入り、試合の録画を見るように自分の一手一手の選択を確認します。このように、AIはプレイヤーの代わりにプレイするのではなく、ゲームの外からプレイヤーが自分自身を理解する手助けをします。",
    "replay_p3": "Replay はまず、ステップごとの評価（スコア）を提示します。プレイヤーは1ゲームの中で損失の大きかった操作を素早く特定できます。問題を見つけると、プレイヤーは自然と「では、この手にもっと良い置き方はあったのか？」と疑問に思うでしょう。そこでシステムは AI が推奨する落下位置を表示し、今後の数手先のルートの参考を示します。これは抽象的なアドバイスではなく、「より良い選択」を直接盤面に提示するものです。",
    "replay_p4": "一方で、プレイヤーはゲーム全体を通してのパフォーマンスも知る必要があります。左側のデータパネルは1ゲーム全体の成績を集計し、レーダーチャートはスピード、攻撃、効率、構造、安定性、視野といった指標を視覚化します。一定期間後にこれらのデータを再比較すれば、少しずつ強くなっているという証拠を確認することができます。",
    "replay_aside_h3": "Replay の設計原則",
    "replay_aside_p": "AI はプレイヤーの操作権を奪うべきではありません。それは試合後のコーチのような存在です。まずプレイヤーに試合を完遂させ、後から問題を指摘し、模範解答を示し、そして成長を記録するのです。",
    "replay_fig1_cap": "Replay のインターフェースは、盤面、タイムライン、AIの推奨、解説パネルを一つにまとめ、プレイヤーが自分の選択を段階的に確認できるよう助けます。",
    "replay_fig2_cap": "1ゲームのサマリーデータにより、そのゲームの全体的なパフォーマンスを知ることができます。",
    "replay_fig3_cap": "レーダーチャートは、様々な能力の指標を比較しやすい一つの形に圧縮します。",
    "replay_note_h3": "1ゲームから長期的な変化へ",
    "replay_note_p": "1ゲームのサマリーは「このゲームで何が起きたか」に答え、レーダーチャートは「能力構造にどんな特徴があるか」に答えます。プレイヤーが繰り返しリプレイ分析を行うことで、毎回の経験を長期的な成長へと繋げることができます。",
    "arch_kicker": "プロジェクト構造",
    "arch_h2": "システム構造：各モジュールは、プレイヤーの成長を軸に一本の線としてつながっています。",
    "arch_title_entry": "ロビー（エントランス）",
    "arch_entry_1": "ソロ練習",
    "arch_entry_2": "知識とシミュレーション演習",
    "arch_entry_3": "試合後分析",
    "arch_entry_4": "1v1 / マルチプレイ",
    "arch_connector": "プレイヤーは各モード間を循環する：練習 → 学習 → リプレイ → 対戦 → 再び練習",
    "arch_layer_1_title": "ゲーム実行レイヤー",
    "arch_layer_1_i1": "10 × 20 の盤面",
    "arch_layer_1_i2": "SRS 回転と Wall Kick",
    "arch_layer_1_i4": "Combo / B2B / T-Spin 判定",
    "arch_layer_2_title": "データ収集レイヤー",
    "arch_layer_2_i1": "毎手の落下位置",
    "arch_layer_2_i2": "盤面スナップショット",
    "arch_layer_2_i3": "ライン消去と攻撃",
    "arch_layer_2_i4": "時間、スピードと操作結果",
    "arch_layer_3_title": "マルチプレイ同期レイヤー",
    "arch_layer_3_i1": "WebSocket サーバー",
    "arch_layer_3_i2": "ルームとプレイヤー状態",
    "arch_layer_3_i3": "攻撃の送受信",
    "arch_layer_3_i4": "1v1 / マルチプレイ拡張",
    "arch_flow_1_title": "対局データ",
    "arch_flow_1_desc": "実際のプレイで生じた毎手の記録",
    "arch_flow_2_title": "分析アルゴリズム",
    "arch_flow_2_desc": "候補ルートを探索し、評価関数でスコアリング",
    "arch_flow_3_title": "Replay の視覚化",
    "arch_flow_3_desc": "タイムライン、推奨落下位置、データパネル、レーダーチャート",
    "arch_support_title": "サポートシステム",
    "arch_support_1_title": "三言語ローカライズ",
    "arch_support_1_desc": "中国語 / 日本語 / 英語",
    "arch_support_2_title": "入力対応",
    "arch_support_2_desc": "キーボードとコントローラー",
    "arch_support_3_title": "素材とUI",
    "arch_support_3_desc": "ロビー、盤面、リプレイ画面",
    "arch_support_4_title": "開発ツールチェーン",
    "arch_support_4_desc": "Agent / MCP / CLI",
    "tech_kicker": "技術的な解説",
    "tech_h2": "技術：AI の中核は、大規模言語モデルではなく「探索と評価」です。",
    "tech_p1": "テトリスのAI分析はチェスや将棋のようなボードゲームに近いです。理由は、プレイヤーが完全にランダムにブロックを受け取るわけではないからです。ルールでは、プレイヤーは次の5つのブロック（NEXT）を見ることができ、Holdを使って1つのブロックを保存できます。つまり、システムはある程度先の盤面を予測し、異なる置き方がもたらす結果を探索することができるのです。",
    "tech_p2": "したがって、ここでのAIの中核にはCNN、RNN、あるいはLLMは必要ありません。AlphaGo時代の考え方に似ており、まず操作の候補を生成し、数手先まで探索してから、評価関数を用いて盤面の質を判断します。評価関数は、10 × 20 の盤面状況を「高さ」「空洞（穴）」「表面の凹凸」「攻撃チャンス」「将来の持続性」など、多くの指標に分解して計算します。",
    "tech_p3": "Replay が特定の手を分析する際、アルゴリズムはプレイヤーの実際の選択と、探索で得られた推奨の選択を比較します。もし両者の差が大きければ、システムはその手が「問題のある操作」だった可能性としてマークします。このように、AI の役割は曖昧な評価を下すことではなく、「この局面におけるより良いルート」を計算し、インターフェースを通じてプレイヤーに提示することです。",
    "tech_p4": "プロジェクト本体は Godot ベースで開発されています。Godot は Unity に似たオープンソースのゲームエンジンですが、より軽量で、2D/3D ゲームのプロトタイプを素早く作成し、継続的に反復するのに適しています。Agent、MCP、CLI ツールと組み合わせることで、小規模なプロジェクトでも UI の変更、フローのデバッグ、ドキュメントの整理、ツールチェーンの拡張をより迅速に行うことができます。",
    "tech_card_1_title": "Godot",
    "tech_card_1_desc": "ゲーム画面、UI、入力、シーン、および主要なゲームプレイのロジックを担当します。",
    "tech_card_2_title": "探索アルゴリズム",
    "tech_card_2_desc": "Next 5 と Hold を中心に、今後の数手先の候補ルートを探索します。",
    "tech_card_3_title": "評価関数",
    "tech_card_3_desc": "盤面構造を複数の指標に分解し、各ルートに対してスコアリングを行います。",
    "tech_card_4_title": "WebSocket",
    "tech_card_4_desc": "オンライン対戦におけるルーム管理、同期、および攻撃の伝達に使用されます。",
    "tech_card_5_title": "開発ツールチェーン",
    "tech_card_5_desc": "Agent / MCP / CLI により、修正、検査、ドキュメント化を迅速に行えます。",
    "closing_label": "おわりに",
    "closing_h2": "システムの最大のポイントは、「プレイヤーが強くなりたい」という思いを、学習可能で、操作可能で、リプレイ（振り返り）可能で、かつ検証可能なプロセスへと分解することにあります。",
    "closing_p": "Guidebook は「何を学ぶべきか、どうやって実際に手を動かすか」という問題を解決し、Replay は「どこが悪かったのか、もっと良い選択肢はなかったか」という問題を解決します。そしてマルチプレイ対戦が最終的な検証の場を提供します。プロジェクト全体は単なる機能の集合体ではなく、プレイヤーの成長を軸に逆算して設計された「上達への道」なのです。"
  },
  "en": {
    "page_title": "Tetris Learning & Replay System | Core Document",
    "nav_foreword": "Foreword",
    "nav_intro": "Intro",
    "nav_origin": "Origin",
    "nav_rules": "Rules",
    "nav_journey": "Journey",
    "nav_guidebook": "Guidebook",
    "nav_replay": "Replay",
    "nav_architecture": "Architecture",
    "nav_tech": "Tech",
    "brand_title": "Tetris Learning System",
    "cover_author": "by WANHENG（バンコウ）",
    "cover_github": "GitHub",
    "cover_download": "Download",
    "cover_label": "Core Document",
    "cover_h1": "Designing a learning and replay system to help players improve, based on the competitive nature of Tetris.",
    "cover_lead": "Tetris is not just about placing blocks in a row to clear them. In competitive play, players must balance offense and defense, plan their placements ahead, make split-second decisions at high speed, and refine their approach through post-match review. Together, these elements form a system of sustained competitive play. This project revolves around \"how players progress from beginners to advanced,\" focusing on the learning system, replay analysis, and overall technical architecture.",
    "cover_flow_1_title": "Foreword",
    "cover_flow_1_desc": "First, explain in plain language why Tetris is competitive.",
    "cover_flow_2_title": "Origin",
    "cover_flow_2_desc": "Players want to improve and beat stronger opponents, but lack sufficiently good auxiliary tools.",
    "cover_flow_3_title": "Design",
    "cover_flow_3_desc": "Solve \"how to learn\" and \"where mistakes are made\" through Guidebook and Replay respectively.",
    "cover_flow_4_title": "Structure",
    "cover_flow_4_desc": "Finally, explain how the game, data collection, AI analysis, multiplayer, and toolchain are combined.",
    "intro_kicker": "Intro: Understanding Tetris first",
    "intro_h2": "Tetris is not just \"placing blocks in a row to clear them.\"",
    "intro_p1": "When many people think of Tetris, they imagine a very simple scene: blocks falling, players aligning them, and clearing a full row. Looking only at this level, it is indeed a single-player puzzle game. However, Tetris, especially the competitive type, has evolved into a system very close to esports.",
    "intro_p2": "In a match, players don't simply pursue \"surviving longer.\" Every line clear can translate into an attack on the opponent. Upon receiving an attack, garbage lines appear at the bottom of the board, pushing the field continuously upwards. Whoever can create pressure faster and handle pressure more stably is closer to victory.",
    "intro_p3": "This is why taking Tetris seriously is no different from training for any competitive discipline. Players must not only build their operation speed, but also understand concepts like attack efficiency, stacking structure, preview judgment, the use of Hold, T-Spin, Combo, and Back-to-Back. These elements interweave to form a competitive system with a genuine learning curve, strategic depth, and real value in post-match review.",
    "intro_aside_h3": "For readers completely unfamiliar with Tetris",
    "intro_aside_p": "The focus of competitive Tetris is not just clearing lines, but converting line clears into pressure and applying that pressure to the opponent. Players must both generate attacks and handle the attacks they receive.",
    "intro_fig1": "When attacked, pressure is first displayed in the attack bar, giving the player a chance to cancel it out by clearing their own lines.",
    "intro_fig2": "If pressure is not handled, the attack turns into garbage lines at the bottom of the board, directly altering the subsequent situation.",
    "intro_footnote": "These two 1v1 images show the basic mechanism: attacks do not appear out of nowhere; they are first displayed as pressure. If the player does not cancel it out through their own line clears, the pressure enters the board, becoming garbage lines that must be dealt with.",
    "origin_kicker": "Project Origin",
    "origin_h2": "Once you understand that, players who want to improve will notice something: there are almost no good learning tools.",
    "origin_p1": "After encountering Tetris, players soon develop a natural goal: not only to survive stably but also to defeat more and stronger opponents in matches. This goal drives players to continue learning attack methods, stacking techniques, T-Spins, Combos, and how to maintain board stability under pressure.",
    "origin_p2": "Existing resources do include Tetris wikis, video tutorials, and community discussions, but these contents are usually more like databases. They can explain concepts, but not necessarily let players immediately jump into a fixed situation to try it themselves; they can showcase expert plays, but not necessarily point out exactly where an ordinary player went wrong in their own match.",
    "origin_p3": "Therefore, the starting point of the system design is not to add another normal mode, but to supplement two types of learning tools: one responsible for connecting knowledge with operation, and one responsible for dismantling and analyzing the player's own matches. The former is the Guidebook, and the latter is the Replay.",
    "origin_aside_h3": "Design Starting Point",
    "origin_aside_p": "What players really need is an operable learning environment and reviewable error analysis. Just reading concepts is not enough, and simply playing repeatedly does not guarantee discovering problems.",
    "rules_kicker": "Minimal explanation of match rules",
    "rules_h2": "To understand its competitive depth, you first need to know one thing: clearing lines is an attack.",
    "rules_p1": "In the common impression, clearing a line is just scoring. But in competitive Tetris, clearing lines is also an act of attack. The more valuable the clear, the greater the pressure exerted on the opponent. For example, clearing four lines at once, which is a Tetris, usually has more attack value than clearing one or two lines scatteredly.",
    "rules_p2": "Going a step further, techniques like T-Spin Double only clear two lines, but due to higher operational difficulty and structural requirements, they can generate attack power close to or even equal to a Tetris in many rules. This is why advanced players proactively learn T-Spins: it's not showing off, but converting limited blocks into attacks more efficiently.",
    "rules_p3": "At the same time, players can also see the next 5 blocks and temporarily store one block in Hold. This makes Tetris no longer just a reaction game, but like a board game, requiring planning several steps ahead.",
    "rules_stack_1_title": "Board",
    "rules_stack_1_desc": "The standard field is 10 columns × 20 rows. The closer to the top, the higher the risk of topping out.",
    "rules_stack_2_title": "Next 5 + Hold",
    "rules_stack_2_desc": "Players can see the upcoming 5 blocks and temporarily store 1 block, meaning every move involves planning.",
    "rules_stack_3_title": "Attacks and Garbage Lines",
    "rules_stack_3_desc": "High-value clears send garbage lines to the opponent. Garbage lines raise the field and compress operable space.",
    "rules_stack_4_title": "Canceling",
    "rules_stack_4_desc": "When about to receive an attack, you can cancel out some pressure by clearing lines, rather than just passively enduring it.",
    "rules_demo_wall_title": "Wall Kick",
    "rules_demo_wall_desc": "When rotation hits the wall, the system tries an offset, letting the L piece slip into the gap.",
    "rules_demo_tspin_title": "T-Spin",
    "rules_demo_tspin_desc": "The T piece enters by rotation and clears 2 lines at the same time.",
    "source_tetris_title": "Strategy Differences Between Expert and Novice Tetris Players",
    "source_tetris_desc": "World-class players reduce unnecessary rotation inputs, while more complex decisions can add initial reaction-time costs. This supports framing Tetris as a real-time task with cognitive load, not a simple reaction game.",
    "source_gla_title": "Collecting, Analyzing, and Visualizing In-Game Behavior Data",
    "source_gla_desc": "Alonso-Fernández et al. (2022) present Game Learning Analytics as a framework for collecting, analyzing, and visualizing player interaction data in serious games. Based on this perspective, this research treats Tetris replay data as a target for analyzing the learning process.",
    "journey_kicker": "Reverse-engineering the system from player needs",
    "journey_h2": "So we started with one question: how do players actually get better, step by step?",
    "journey_step1_h3": "First, players need to know what they are playing.",
    "journey_step1_p": "What beginners need first are not complex techniques, but basic knowledge: board structure, block types, Hold, Next, clearing lines, attacks, garbage lines, and why some clears are more valuable.",
    "journey_step2_h3": "Then, players need a safe place to practice alone.",
    "journey_step2_p": "The single-player Marathon mode takes on this role. Players can get familiar with operations, stacking, rhythm, and speed without interference. The goal here is \"can I play stably?\"",
    "journey_step3_h3": "Next, players will start thinking about how to play better.",
    "journey_step3_p": "This is where the Guidebook comes in. It explains the principles behind Wall Kick, Combo, T-Spin, etc., and lets players actually practice them on preset boards via simulation drills.",
    "journey_step4_h3": "Further on, players want to know what they did wrong.",
    "journey_step4_p": "Playing more might just repeat mistakes. Replay breaks down the match, using AI recommendations to quickly spot weaknesses and guide future practice.",
    "journey_step5_h3": "Finally, players need to confirm their progress.",
    "journey_step5_p": "Players can confirm their growth through long-term data, radar charts, and match results. Progress is sometimes small and hard to feel, but data preserves these changes.",
    "guide_kicker": "Guidebook: From knowing concepts to hands-on experience",
    "guide_h2": "The first answer \u2014 solve \"how to learn\": let players practice hands-on, not just read tutorials.",
    "guide_p1": "Many players have seen videos of T-Spin or Combo, but back in the game, they still don't know how to set them up. The reason is simple: Tetris techniques require performing the actual moves on the board to truly grasp why they work.",
    "guide_p2": "Therefore, the Guidebook is not a manual but a learning entry point. It explains techniques simply, gives required background, and lets players enter a simulation drill where conditions are fixed to focus on one concept.",
    "guide_p3": "The purpose is to break down learning pressure. Players don't need to wait for the right moment in a real match or learn while being attacked. They can perform the core action correctly once in a controlled scenario.",
    "guide_module_1_title": "Basic Knowledge",
    "guide_module_1_desc": "Clarify rules like attack power, garbage lines, canceling, B2B, and Combos.",
    "guide_module_2_title": "Operation Chapters",
    "guide_module_2_desc": "Break down Wall Kick, Combo, T-Spin Double into small, learnable chapters.",
    "guide_module_3_title": "Simulation Drills",
    "guide_module_3_desc": "Players enter a fixed situation and complete a target move with real inputs.",
    "guide_module_4_title": "Feedback",
    "guide_module_4_desc": "The system checks if the goal was met, letting players know if their move worked.",
    "guide_annotation_title": "Guidebook Page Example",
    "guide_annotation_desc": "This annotated screenshot shows how chapter copy, knowledge cards, and the simulation entry work together on one page.",
    "replay_kicker": "Replay: Turning 'felt like I played okay' into observable data",
    "replay_h2": "The second answer \u2014 solve \"what went wrong\": AI reviews the match afterward, instead of playing for you.",
    "replay_p1": "If AI constantly hints where to place during a game, it might seem convenient, but it disrupts player judgment. Independent choice under pressure is a core joy of Tetris.",
    "replay_p2": "Therefore, AI's main role is after the match. Players play fully, preserving the experience, then enter Replay to review choices like watching a sports tape.",
    "replay_p3": "Replay first gives step-by-step scoring. Players locate bad moves quickly, wonder \"is there a better way?\" and the system shows the AI recommended spot and route.",
    "replay_p4": "Also, players need overall performance. Data panels summarize the match, and radar charts visualize dimensions like speed, attack, efficiency, structure, stability, and vision.",
    "replay_aside_h3": "Replay Design Principles",
    "replay_aside_p": "AI shouldn't hijack player controls. It's more like a post-match coach: let the player finish, then point out mistakes, show reference answers, and record progress.",
    "replay_fig1_cap": "The Replay UI combines board, timeline, AI recommendations, and explanations to help players check their choices step-by-step.",
    "replay_fig2_cap": "Match summary data lets players know how their overall performance was.",
    "replay_fig3_cap": "Radar charts compress different ability dimensions into an easily comparable shape.",
    "replay_note_h3": "From single match to long-term change",
    "replay_note_p": "Match summaries answer \"what happened this game,\" while radar charts answer \"what are my skill characteristics.\" Repeated replays connect single-game experiences into long-term progress.",
    "arch_kicker": "Project Structure",
    "arch_h2": "These modules don't stand alone \u2014 they form a single path built around player growth.",
    "arch_title_entry": "Lobby Entry",
    "arch_entry_1": "Solo Practice",
    "arch_entry_2": "Knowledge & Drills",
    "arch_entry_3": "Post-match Analysis",
    "arch_entry_4": "1v1 / Multiplayer",
    "arch_connector": "Players loop through modes: Practice → Learn → Replay → Match → Practice again",
    "arch_layer_1_title": "Game Engine Layer",
    "arch_layer_1_i1": "10 × 20 Board",
    "arch_layer_1_i2": "SRS Rotation & Wall Kick",
    "arch_layer_1_i4": "Combo / B2B / T-Spin Logic",
    "arch_layer_2_title": "Data Collection Layer",
    "arch_layer_2_i1": "Per-step placement",
    "arch_layer_2_i2": "Board snapshots",
    "arch_layer_2_i3": "Line clears and attacks",
    "arch_layer_2_i4": "Time, speed, operation results",
    "arch_layer_3_title": "Multiplayer Sync Layer",
    "arch_layer_3_i1": "WebSocket Server",
    "arch_layer_3_i2": "Rooms and player states",
    "arch_layer_3_i3": "Attack send/receive",
    "arch_layer_3_i4": "1v1 / Multiplayer extensions",
    "arch_flow_1_title": "Match Data",
    "arch_flow_1_desc": "Step-by-step logs from actual play",
    "arch_flow_2_title": "Analysis Algorithm",
    "arch_flow_2_desc": "Search candidate routes & score via evaluation function",
    "arch_flow_3_title": "Replay Visualization",
    "arch_flow_3_desc": "Timeline, recommended drops, data panels, radar charts",
    "arch_support_title": "Support System",
    "arch_support_1_title": "Trilingual Localization",
    "arch_support_1_desc": "CN / JA / EN",
    "arch_support_2_title": "Input Support",
    "arch_support_2_desc": "Keyboard & Gamepad",
    "arch_support_3_title": "Assets & UI",
    "arch_support_3_desc": "Lobby, board, replay interface",
    "arch_support_4_title": "Dev Toolchain",
    "arch_support_4_desc": "Agent / MCP / CLI",
    "tech_kicker": "Technical Explanation",
    "tech_h2": "Finally, the tech: the AI here doesn't rely on large language models, but on search and evaluation.",
    "tech_p1": "Tetris AI analysis is closer to board games. Players don't receive blocks blindly: rules allow seeing the next 5 blocks and holding one. This means the system can predict future situations and search the results of different placements.",
    "tech_p2": "Therefore, the core AI doesn't need CNNs, RNNs, or LLMs. It's more like AlphaGo: generate candidate operations, search ahead, and judge board quality via an evaluation function.",
    "tech_p3": "When Replay analyzes a step, it compares the player's choice with the recommended one. If the gap is large, it marks it as a potential mistake.",
    "tech_p4": "The project is built on Godot, an open-source game engine. Combined with tools like Agent, MCP, and CLI, it allows rapid UI modification, flow debugging, and toolchain extension.",
    "tech_card_1_title": "Godot",
    "tech_card_1_desc": "Handles graphics, UI, input, scenes, and gameplay logic.",
    "tech_card_2_title": "Search Algorithm",
    "tech_card_2_desc": "Searches future routes around Next 5 and Hold.",
    "tech_card_3_title": "Evaluation Function",
    "tech_card_3_desc": "Breaks board structure into metrics and scores each route.",
    "tech_card_4_title": "WebSocket",
    "tech_card_4_desc": "Used for online rooms, sync, and passing attacks.",
    "tech_card_5_title": "Dev Toolchain",
    "tech_card_5_desc": "Agent / MCP / CLI help quickly complete modifications, checks, and docs.",
    "closing_label": "Closing",
    "closing_h2": "The focus of the system is to break down \"players wanting to get stronger\" into a learnable, operable, replayable, and verifiable process.",
    "closing_p": "Guidebook solves \"what to learn and how to do it\"; Replay solves \"what was bad and are there better choices\"; multiplayer provides the final validation. It's a path designed around player growth."
  }
};

Object.assign(translations["ja"], {
  "nav_intro": "背景",
  "nav_rules": "問題",
  "nav_origin": "目的",
  "nav_journey": "システム",
  "nav_replay": "Replay分析",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "実装",
  "nav_tech": "今後の課題",
  "cover_h1": "対戦型テトリス初心者の振り返りを支援するリプレイ分析システム",
  "cover_lead": "対戦型テトリスでは、プレイヤーは短時間の中で、ブロックの配置、攻撃、防御、相殺、NEXT と Hold の利用など、複数の要素を同時に判断する必要がある。そのため、初心者は対局後にリプレイを見ても、どの場面で判断を誤ったのか、どのような置き方がより良かったのかを理解しにくい。本研究では、この問題に対して、プレイ中の盤面状態や操作記録を保存し、試合後に一手ごとの判断を可視化するリプレイ分析システムを開発した。",
  "cover_flow_1_title": "背景",
  "cover_flow_1_desc": "対戦型テトリスが複数の判断を高速に行う競技的なゲームであることを説明する。",
  "cover_flow_2_title": "問題",
  "cover_flow_2_desc": "初心者はリプレイを見ても、なぜ負けたのか、どこを改善すべきかを理解しにくい。",
  "cover_flow_3_title": "システム",
  "cover_flow_3_desc": "リプレイ分析を中心に、操作の問題を可視化し、必要な練習へ導く。",
  "cover_flow_4_title": "実装と課題",
  "cover_flow_4_desc": "データ記録、AI評価、可視化、今後の評価実験を説明する。",
  "intro_kicker": "背景：対戦型テトリスの競技性",
  "intro_h2": "対戦型テトリスでは、短時間で複数の判断を同時に行う必要があります。",
  "intro_p1": "多くの人にとって、テトリスは「落ちてくるブロックを並べ、一列揃えて消す」ゲームとして理解されています。しかし対戦型テトリスでは、ライン消去は得点だけでなく相手への攻撃にもつながります。プレイヤーは自分の盤面を整えながら、相手へ送る攻撃量と、自分が受ける攻撃への対応を同時に考える必要があります。",
  "intro_p2": "さらに、プレイヤーは NEXT と Hold を利用して数手先を予測し、T-Spin、Combo、Back-to-Back、相殺などの要素を状況に応じて選択します。つまり、対戦型テトリスは単純な反射ゲームではなく、配置判断、攻撃、防御、先読みが短時間に圧縮されたリアルタイム課題です。",
  "intro_p3": "そのため、初心者が上達するには、単に何度もプレイするだけではなく、自分のプレイを後から見直し、どの判断がよく、どの判断が問題だったのかを理解することが重要になります。本研究では、この「振り返り」に焦点を当てます。",
  "intro_aside_h3": "代表的な操作例",
  "intro_aside_p": "Wall Kick や T-Spin のような技術は、対戦型テトリスに配置判断と操作戦略が含まれることを示す例である。",
  "rules_kicker": "問題：初心者の振り返りの難しさ",
  "rules_h2": "初心者は、リプレイを見ても「なぜ負けたのか」「どこを改善すべきか」を理解しにくい。",
  "rules_p1": "既存の学習方法として、Wiki、動画チュートリアル、コミュニティでの解説などがあります。これらは一般的な知識や上級者のプレイを学ぶには有効ですが、プレイヤー自身の対局における具体的な判断やミスを示すことは難しいという限界があります。",
  "rules_p2": "特に初心者は、リプレイを見ても「どの場面で判断を誤ったのか」「どのような置き方がより良かったのか」を自力で判断しにくいです。盤面の高さ、空洞、攻撃のタイミング、相殺の判断などが同時に関係するため、問題の原因が一手だけに見えないことも多くあります。",
  "rules_p3": "その結果、初心者は同じような負け方や低効率な操作を繰り返し、安定した次善策を習慣化してしまう可能性があります。したがって、単にリプレイを再生するだけでなく、一手ごとの判断をデータとして整理し、改善点を見つけやすくする支援が必要です。",
  "rules_stack_1_title": "一般知識はある",
  "rules_stack_1_desc": "Wiki や動画は概念説明には強いが、自分の対局のどの手が問題だったかまでは示しにくい。",
  "rules_stack_2_title": "原因が見えにくい",
  "rules_stack_2_desc": "負けた直接原因はトップアウトでも、その前の置き方、攻撃判断、相殺判断が影響している。",
  "rules_stack_3_title": "低効率な習慣",
  "rules_stack_3_desc": "反復練習だけでは、安定しているが効率の低い操作を固定してしまう可能性がある。",
  "rules_stack_4_title": "必要な支援",
  "rules_stack_4_desc": "リプレイを、単なる録画ではなく、判断を可視化する分析データとして扱う必要がある。",
  "rules_demo_wall_title": "従来の学習方法の限界",
  "rules_demo_wall_desc": "一般的な解説は「何をすべきか」を説明できますが、「あなたのこの対局では、どの一手がなぜ悪かったのか」を自動的には示せません。",
  "rules_demo_tspin_title": "研究上の問題定義",
  "rules_demo_tspin_desc": "初心者が自分の対局を振り返り、ミスや改善点を発見するためには、プレイデータに基づく可視化と分析が必要です。",
  "origin_kicker": "目的：リプレイ分析による振り返り支援",
  "origin_h2": "本研究の目的は、初心者が自分のプレイを理解し、改善点を発見できるようにすることです。",
  "origin_p1": "本研究では、対戦型テトリス初心者が自分の対局を振り返り、ミスや改善点を理解できるようにすることを目的とします。そのために、プレイ中の操作記録、盤面状態、攻撃・防御の状況を保存し、試合後に一手ごとの判断を可視化するリプレイ分析システムを開発しました。",
  "origin_p2": "Lindstedt and Gray（2020）は、Tetris を高速なリアルタイム課題として扱い、初心者と熟練者の操作戦略に差があることを示しています。このことは、Tetris の上達が単なる操作速度だけでなく、認知的負荷を伴う戦略選択とも関係することを示唆しています。",
  "origin_p3": "また、Alonso-Fernández et al.（2022）は、ゲーム内行動データを収集・分析・可視化する Game Learning Analytics の有用性を示しています。したがって、本研究では Tetris のリプレイデータを学習分析の対象として扱い、初心者が自分の判断過程を理解するための支援に用います。",
  "origin_aside_h3": "研究の中心",
  "origin_aside_p": "中心となるのは Replay 分析です。Guidebook は別の主役ではなく、分析結果を理解するための前提知識を補う機能として位置づけます。AI も独立した主役ではなく、一手ごとの比較と評価を行う分析方法として扱います。",
  "journey_kicker": "システムの全体像",
  "journey_h2": "Replay 分析を中心に、基礎理解、試合後分析、改善練習を一つの流れとして接続します。",
  "journey_step1_h3": "対局データを記録する",
  "journey_step1_p": "プレイ中の盤面、落下位置、消去、攻撃、時間、操作結果を保存し、試合後に分析できる形にします。",
  "journey_step2_h3": "一手ごとに可視化する",
  "journey_step2_p": "リプレイ画面で盤面、タイムライン、攻撃状況、AI 推奨手を並べ、どの場面が問題だったかを確認できるようにします。",
  "journey_step3_h3": "改善点を発見する",
  "journey_step3_p": "実際の選択と推奨手を比較し、地形悪化、攻撃機会の損失、相殺判断の遅れなどを見つけます。",
  "journey_step4_h3": "Guidebook で補助学習する",
  "journey_step4_p": "分析結果を理解するために必要な T-Spin、Combo、相殺などを、小さなシミュレーションで確認できるようにします。",
  "journey_step5_h3": "変化を確認する",
  "journey_step5_p": "単局サマリーやレーダーチャートで、速度、攻撃、効率、安定性などの変化を長期的に確認します。",
  "replay_kicker": "Replay分析：一手ごとの判断を可視化する",
  "replay_h2": "AI は対局中に操作を指示するのではなく、試合後にプレイヤーの判断を分析します。",
  "replay_p1": "本システムでは、AI が対局中に操作を指示するのではなく、試合後にプレイヤーの選択を分析します。これにより、プレイヤー本来の判断を妨げずに、対局後の振り返りを支援できます。",
  "replay_p2": "Replay では、各手の盤面状態、落下位置、ライン消去、攻撃量、地形変化を確認できます。プレイヤーは試合全体をただ眺めるのではなく、どの一手がその後の不利な状況につながったのかを段階的に追うことができます。",
  "replay_p3": "AI 評価では、プレイヤーの実際の置き方と、探索によって得られた推奨手を比較します。差が大きい手を候補として示すことで、初心者が「この場面では何を見落としていたのか」を考えやすくします。",
  "replay_p4": "また、単局サマリーやレーダーチャートにより、速度、攻撃、効率、構造、安定性、視野などを確認できます。これにより、個別のミスだけでなく、長期的な成長傾向も把握できます。",
  "replay_aside_h3": "設計原則",
  "replay_aside_p": "AI はプレイヤーの操作権を奪うものではなく、試合後のコーチとして働きます。目的は「代わりにプレイすること」ではなく、「プレイヤーが自分の判断を理解できるようにすること」です。",
  "guide_kicker": "Guidebook：分析結果を理解するための基礎学習",
  "guide_h2": "Guidebook は Replay 分析を理解するための補助教材として位置づけます。",
  "guide_p1": "初心者が Replay 分析の結果を理解するためには、T-Spin、Combo、相殺、攻撃価値、NEXT/Hold などの基礎知識が必要です。これらを知らないままでは、AI が示した推奨手や評価の意味を理解しにくくなります。",
  "guide_p2": "そこで Guidebook では、基本ルールや代表的なテクニックを小さな章に分け、アニメーションと固定局面のシミュレーションで確認できるようにします。目的は知識を増やすこと自体ではなく、Replay で見つかった課題を理解し、次の練習へつなげることです。",
  "guide_p3": "たとえば Replay で T-Spin の機会を逃していた場合、Guidebook の T-Spin 章に戻り、構造と操作を固定局面で確認できます。このように Guidebook は、Replay 分析を中心とした学習サイクルを支える補助機能です。",
  "arch_kicker": "実装：プレイデータの記録・評価・可視化",
  "arch_h2": "Replay 分析を実現するために、各手の状態を記録し、評価し、画面上に可視化します。",
  "arch_title_entry": "分析に必要なデータ",
  "arch_entry_1": "盤面スナップショット",
  "arch_entry_2": "操作と落下位置",
  "arch_entry_3": "消去・攻撃・相殺",
  "arch_entry_4": "速度と手順",
  "arch_connector": "対局中に記録したデータを、試合後に Replay 画面で再構成し、AI 評価と可視化に利用します。",
  "arch_layer_3_title": "分析・可視化レイヤー",
  "arch_layer_3_i1": "AI 推奨手との比較",
  "arch_layer_3_i2": "タイムライン表示",
  "arch_layer_3_i3": "単局サマリー",
  "arch_layer_3_i4": "レーダーチャート",
  "arch_support_title": "実装補足",
  "arch_support_4_title": "オンライン対戦",
  "arch_support_4_desc": "オンライン対戦データも収集している",
  "tech_kicker": "今後の課題：評価実験と分析精度の改善",
  "tech_h2": "今後は、本システムが初心者の振り返りを本当に支援できるかを検証する必要があります。",
  "tech_p1": "現段階では、リプレイ分析の仕組みと可視化インターフェースを実装しています。次の課題は、初心者がこのシステムを使うことで、自分のミスや改善点をより理解しやすくなるかを評価することです。",
  "tech_p2": "評価方法としては、システム使用前後で、プレイヤーが自分のミスを説明できるか、推奨手の意味を理解できるか、同じ種類のミスを減らせるかを確認する必要があります。アンケートや簡単なプレイ課題を組み合わせることで、学習支援としての有効性を検証できます。",
  "tech_p3": "また、AI 評価の精度も改善の余地があります。現状の評価関数は、盤面の高さ、空洞、攻撃機会などをもとにルートを評価しますが、初心者にとって理解しやすい説明へ変換するには、評価理由をより明確に示す必要があります。",
  "tech_p4": "さらに、オンライン対戦機能は現時点では主題ではなく、将来的に多様なプレイデータを収集し、分析対象を広げるための拡張機能として位置づけます。本研究ではまず、リプレイ分析による初心者の振り返り支援に焦点を絞ります。",
  "tech_card_1_title": "評価実験",
  "tech_card_1_desc": "初心者がミスや改善点を説明しやすくなるかを確認する。",
  "tech_card_2_title": "分析精度",
  "tech_card_2_desc": "推奨手と評価関数が初心者の改善に役立つかを検証する。",
  "tech_card_3_title": "説明性",
  "tech_card_3_desc": "なぜその手が良いのかを、盤面指標と自然な説明で示す。",
  "tech_card_4_title": "Guidebook 連携",
  "tech_card_4_desc": "分析結果から関連する基礎章へ自然に接続する。",
  "tech_card_5_title": "データ拡張",
  "tech_card_5_desc": "収集済みのオンライン対戦データを評価・分析に活用する。",
  "closing_h2": "本研究の中心は、初心者が自分の対局を理解し、改善点を発見するための Replay 分析支援です。",
  "closing_p": "従来は、初心者が自分のリプレイを見ても、具体的にどの判断が問題だったのかを理解しにくいという課題がありました。そこで本研究では、盤面・操作・攻撃状況を記録し、試合後に一手ごとの判断を可視化する Replay 分析システムを開発しました。Guidebook や AI 評価は、この中心目的を支えるための補助要素として位置づけます。"
});

Object.assign(translations["zh-CN"], {
  "nav_intro": "背景",
  "nav_rules": "问题",
  "nav_origin": "目的",
  "nav_journey": "系统",
  "nav_replay": "Replay分析",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "实现",
  "nav_tech": "今后课题",
  "cover_h1": "面向对战型 Tetris 初学者的 Replay 分析支援系统",
  "cover_lead": "对战型 Tetris 要求玩家在短时间内同时判断方块放置、攻击、防守、抵消、NEXT 与 Hold 等因素。因此，初学者即使赛后观看 replay，也很难理解自己在哪个场面判断错误、怎样放会更好。本研究针对这一问题，提出保存盘面状态与操作记录，并在赛后可视化每一步判断的 Replay 分析系统。",
  "cover_flow_2_title": "问题",
  "cover_flow_2_desc": "初学者看 replay 时，很难理解自己为什么输、应该改善哪里。",
  "cover_flow_3_title": "系统",
  "cover_flow_3_desc": "以 Replay 分析为中心，可视化操作问题，并连接到必要练习。",
  "intro_kicker": "背景：对战型 Tetris 的竞技性",
  "intro_h2": "对战型 Tetris 需要在短时间内同时进行多个判断。",
  "rules_kicker": "问题：初学者复盘困难",
  "rules_h2": "初学者即使观看 replay，也很难理解“为什么输”和“该改善哪里”。",
  "origin_kicker": "目的：通过 Replay 分析支援复盘",
  "origin_h2": "本研究的目的是帮助初学者理解自己的 play，并发现改善点。",
  "journey_kicker": "系统整体",
  "journey_h2": "以 Replay 分析为中心，连接基础理解、赛后分析与改善练习。",
  "replay_kicker": "Replay分析：可视化每一步判断",
  "replay_h2": "AI 不在对局中指示操作，而是在赛后分析玩家判断。",
  "guide_kicker": "Guidebook：理解分析结果所需的基础学习",
  "guide_h2": "Guidebook 是帮助理解 Replay 分析的辅助教材。",
  "arch_kicker": "实现：记录、评价、可视化 play 数据",
  "arch_h2": "为了实现 Replay 分析，系统记录每一步状态，进行评价，并在界面中可视化。",
  "tech_kicker": "今后课题：评价实验与分析精度改善",
  "tech_h2": "下一步需要验证该系统是否真的能帮助初学者复盘。",
  "closing_h2": "本研究的中心是帮助初学者理解自己的对局并发现改善点的 Replay 分析支援。",
  "closing_p": "以往初学者即使观看自己的 replay，也很难理解具体是哪一个判断出了问题。因此本研究提出记录盘面、操作和攻击状况，并在赛后可视化每一步判断的 Replay 分析系统。Guidebook 与 AI 评价都作为支撑这一中心目的的辅助要素。"
});

Object.assign(translations["en"], {
  "nav_intro": "Background",
  "nav_rules": "Problem",
  "nav_origin": "Purpose",
  "nav_journey": "Proposal",
  "nav_replay": "Replay Analysis",
  "nav_guidebook": "Guidebook",
  "nav_architecture": "Implementation",
  "nav_tech": "Future Work",
  "cover_h1": "A Replay Analysis Support System for Beginner Competitive Tetris Players",
  "cover_lead": "Competitive Tetris requires players to judge placements, attacks, defense, canceling, NEXT, and Hold within a short time. Beginners often cannot tell, even after watching a replay, where their judgment failed or what placement would have been better. This research proposes a replay analysis system that records board states and inputs during play, then visualizes each decision after the match.",
  "cover_flow_2_title": "Problem",
  "cover_flow_2_desc": "Beginners have difficulty understanding why they lost and what they should improve from replay alone.",
  "cover_flow_3_title": "Proposal",
  "cover_flow_3_desc": "Replay analysis visualizes decision problems and connects them to necessary practice.",
  "intro_kicker": "Background: Competitive Tetris",
  "intro_h2": "Competitive Tetris requires multiple decisions within a short time.",
  "rules_kicker": "Problem: Replay Reflection Is Difficult",
  "rules_h2": "Beginners struggle to understand why they lost or what to improve, even when watching replay.",
  "origin_kicker": "Purpose: Supporting Reflection Through Replay Analysis",
  "origin_h2": "The goal is to help beginners understand their own play and discover improvements.",
  "journey_kicker": "System Overview",
  "journey_h2": "The system centers on Replay analysis and connects understanding, review, and practice.",
  "replay_kicker": "Replay Analysis: Visualizing Each Decision",
  "replay_h2": "AI analyzes the player's decisions after the match instead of directing play during it.",
  "guide_kicker": "Guidebook: Basic Learning for Understanding Analysis",
  "guide_h2": "Guidebook is positioned as support material for understanding Replay analysis.",
  "arch_kicker": "Implementation: Recording, Evaluating, and Visualizing Play Data",
  "arch_h2": "To realize Replay analysis, the system records each move, evaluates it, and visualizes it on screen.",
  "tech_kicker": "Future Work: Evaluation and Analysis Accuracy",
  "tech_h2": "The next step is to verify whether the system truly supports beginner reflection.",
  "closing_h2": "The core of this research is Replay analysis support for helping beginners understand their matches and find improvements.",
  "closing_p": "Traditionally, beginners may watch their own replay but still struggle to understand which decisions were problematic. This research proposes a Replay analysis system that records board, input, and attack states, then visualizes each decision after the match. Guidebook and AI evaluation support this central purpose."
});

Object.assign(translations["zh-CN"], {
  "intro_p1": "很多人会把 Tetris 理解为把下落方块排成一行再消除的游戏。但在对战型 Tetris 中，消行不仅是得分，也会转化为对对手的攻击。玩家需要一边整理自己的盘面，一边考虑如何制造攻击以及如何处理自己收到的攻击。",
  "intro_p2": "玩家还需要利用 NEXT 和 Hold 预测后续局面，并根据情况选择 T-Spin、Combo、Back-to-Back、抵消等策略。因此，对战型 Tetris 不是简单反应游戏，而是把放置判断、攻击、防守和预判压缩在短时间内的实时任务。",
  "intro_p3": "所以，初学者要进步，不能只靠反复游玩，还需要在赛后回看自己的 play，理解哪些判断有效、哪些判断造成了问题。本研究聚焦于这种“复盘”。",
  "intro_aside_h3": "代表性操作示例",
  "intro_aside_p": "Wall Kick 与 T-Spin 展示了对战型 Tetris 中的放置判断与操作策略。",
  "rules_p1": "已有学习方式包括 Wiki、视频教程和社区解说。这些方式适合学习一般知识或高手操作，但很难指出玩家自己对局中具体哪一步判断或操作出了问题。",
  "rules_p2": "尤其对初学者来说，即使看 replay，也很难判断自己在哪个场面判断错误、怎样放会更好。盘面高度、空洞、攻击时机、抵消判断往往同时作用，问题原因不一定只出现在最后一步。",
  "rules_p3": "结果是，初学者可能重复相似失败方式，并把稳定但低效的操作习惯固定下来。因此 replay 不应只是录像回放，还需要被整理为能可视化判断的数据。",
  "rules_stack_1_title": "一般知识存在",
  "rules_stack_1_desc": "Wiki 和视频擅长解释概念，但难以指出自己对局中哪一步有问题。",
  "rules_stack_2_title": "原因不明显",
  "rules_stack_2_desc": "直接原因可能是死亡，但更早的放置、攻击和抵消判断也可能造成影响。",
  "rules_stack_3_title": "低效习惯",
  "rules_stack_3_desc": "单纯反复练习可能会固定稳定但低效率的操作方式。",
  "rules_stack_4_title": "需要支援",
  "rules_stack_4_desc": "需要把 replay 当成可视化判断过程的分析数据，而不是普通录像。",
  "rules_demo_wall_title": "传统学习方式的限制",
  "rules_demo_wall_desc": "一般教程可以说明应该做什么，却不能自动指出你这一局中哪一步为什么不好。",
  "rules_demo_tspin_title": "研究问题定义",
  "rules_demo_tspin_desc": "为了让初学者发现自己的错误和改善点，需要基于 play 数据的可视化与分析。",
  "origin_p1": "本研究旨在帮助对战型 Tetris 初学者回顾自己的对局，理解错误和改善点。为此，系统保存游玩中的操作记录、盘面状态、攻防状况，并在赛后可视化每一步判断。",
  "origin_p2": "Lindstedt and Gray（2020）将 Tetris 作为高速实时任务，指出初学者与熟练者在操作策略上存在差异。这说明 Tetris 的进步不仅与操作速度有关，也与带有认知负荷的策略选择有关。",
  "origin_p3": "Alonso-Fernández et al.（2022）说明了收集、分析、可视化游戏内行为数据的 Game Learning Analytics 的有效性。因此，本研究将 Tetris replay 数据作为学习分析对象，用于帮助初学者理解自己的判断过程。",
  "origin_aside_h3": "研究中心",
  "origin_aside_p": "中心是 Replay 分析。Guidebook 是帮助理解分析结果的基础知识补充，AI 是用于比较和评价每一步的分析方法。",
  "journey_step1_h3": "记录对局数据",
  "journey_step1_p": "保存游玩中的盘面、落点、消行、攻击、时间和操作结果，使其可在赛后分析。",
  "journey_step2_h3": "可视化每一步",
  "journey_step2_p": "在 Replay 界面并列显示盘面、时间线、攻击状况和 AI 推荐手，帮助定位问题场面。",
  "journey_step3_h3": "发现改善点",
  "journey_step3_p": "比较实际选择和推荐手，发现地形恶化、攻击机会损失、抵消判断延迟等问题。",
  "journey_step4_h3": "用 Guidebook 辅助学习",
  "journey_step4_p": "通过小型模拟确认 T-Spin、Combo、抵消等理解分析结果所需的基础知识。",
  "journey_step5_h3": "确认变化",
  "journey_step5_p": "通过单局总结和雷达图长期确认速度、攻击、效率和稳定性等变化。",
  "replay_p1": "本系统中，AI 不在对局中指示操作，而是在赛后分析玩家选择。这样既不干扰玩家原本判断，也能支援赛后复盘。",
  "replay_p2": "Replay 中可以确认每一步的盘面状态、落点、消行、攻击量和地形变化。玩家不只是观看整局，而是逐步追踪哪一步导致后续不利。",
  "replay_p3": "AI 评价会比较玩家实际放法和搜索得到的推荐手。差距较大的手会被提示，帮助初学者思考自己在该场面漏看了什么。",
  "replay_p4": "单局总结和雷达图还能展示速度、攻击、效率、结构、稳定性和视野等指标，帮助玩家理解长期成长。",
  "guide_p1": "初学者要理解 Replay 分析结果，需要知道 T-Spin、Combo、抵消、攻击价值、NEXT/Hold 等基础知识。",
  "guide_p2": "因此 Guidebook 把基本规则和代表技巧拆成小章节，通过动画和固定局面模拟来确认。它的目的不是单独增加知识，而是帮助理解 Replay 中发现的问题。",
  "guide_p3": "例如 Replay 显示错过 T-Spin 机会时，玩家可以回到 Guidebook 的 T-Spin 章节，在固定局面中确认结构和操作。",
  "arch_title_entry": "分析所需数据",
  "arch_entry_1": "盘面快照",
  "arch_entry_2": "操作与落点",
  "arch_entry_3": "消行、攻击、抵消",
  "arch_entry_4": "速度与步骤",
  "arch_connector": "对局中记录的数据会在赛后 Replay 界面重建，并用于 AI 评价与可视化。",
  "arch_layer_3_title": "分析与可视化层",
  "arch_layer_3_i1": "与 AI 推荐手比较",
  "arch_layer_3_i2": "时间线显示",
  "arch_layer_3_i3": "单局总结",
  "arch_layer_3_i4": "雷达图",
  "arch_support_title": "实现补充",
  "arch_support_4_title": "在线对战",
  "arch_support_4_desc": "未来也可扩展为评价用数据来源",
  "tech_p1": "目前已经实现 Replay 分析机制和可视化界面。下一步要验证初学者使用后是否更容易理解自己的错误和改善点。",
  "tech_p2": "评价方式可以包括系统使用前后，玩家是否能解释自己的错误、是否理解推荐手、是否减少同类错误等。",
  "tech_p3": "AI 评价精度也需要改进。目前评价函数基于高度、空洞、攻击机会等指标，但还需要把评价理由转换为初学者容易理解的说明。",
  "tech_p4": "在线对战目前不是主轴，而是未来扩展数据来源的功能。本研究首先聚焦 Replay 分析对初学者复盘的支援。",
  "tech_card_1_title": "评价实验",
  "tech_card_1_desc": "确认初学者是否更容易说明错误和改善点。",
  "tech_card_2_title": "分析精度",
  "tech_card_2_desc": "验证推荐手和评价函数是否真的帮助改善。",
  "tech_card_3_title": "解释性",
  "tech_card_3_desc": "用盘面指标和自然说明解释为什么这一步更好。",
  "tech_card_4_title": "Guidebook 联动",
  "tech_card_4_desc": "从分析结果自然连接到相关基础章节。",
  "tech_card_5_title": "数据扩展",
  "tech_card_5_desc": "未来把在线对战数据也加入分析对象。"
});

Object.assign(translations["en"], {
  "intro_p1": "Many people understand Tetris as arranging falling blocks and clearing lines. In competitive Tetris, however, line clears also become attacks. Players must organize their own board while considering how much pressure to send and how to respond to incoming pressure.",
  "intro_p2": "Players also use NEXT and Hold to predict future positions and choose T-Spins, Combos, Back-to-Backs, and canceling depending on the situation. Competitive Tetris is therefore not a simple reaction game, but a real-time task compressing placement, attack, defense, and planning into a short time window.",
  "intro_p3": "For beginners to improve, merely playing repeatedly is not enough. They need to review their own play afterward and understand which decisions worked and which caused problems. This research focuses on that reflection process.",
  "intro_aside_h3": "Representative Techniques",
  "intro_aside_p": "Wall Kick and T-Spin show that competitive Tetris involves placement decisions and operation strategies.",
  "rules_p1": "Existing learning methods include wikis, video tutorials, and community explanations. These are useful for general knowledge or expert examples, but they do not easily point out the specific decisions or mistakes in a player's own match.",
  "rules_p2": "Beginners especially struggle to judge where their decision failed or what placement would have been better. Board height, holes, attack timing, and canceling decisions often interact, so the cause is not always the final move.",
  "rules_p3": "As a result, beginners may repeat similar losses and stabilize inefficient habits. Replay should therefore be treated not merely as video playback, but as analysis data that visualizes decisions.",
  "rules_stack_1_title": "General Knowledge Exists",
  "rules_stack_1_desc": "Wikis and videos explain concepts well, but rarely show which move in your match was problematic.",
  "rules_stack_2_title": "Causes Are Hard to See",
  "rules_stack_2_desc": "The direct cause may be topping out, but earlier placement, attack, and canceling decisions may have shaped it.",
  "rules_stack_3_title": "Inefficient Habits",
  "rules_stack_3_desc": "Repeated practice alone can reinforce stable but inefficient play patterns.",
  "rules_stack_4_title": "Needed Support",
  "rules_stack_4_desc": "Replay must become analysis data that visualizes decisions, not just match footage.",
  "rules_demo_wall_title": "Limit of Traditional Learning",
  "rules_demo_wall_desc": "General tutorials can explain what to do, but cannot automatically explain why a specific move in your match was bad.",
  "rules_demo_tspin_title": "Research Problem",
  "rules_demo_tspin_desc": "Beginners need data-based visualization and analysis to find mistakes and improvements in their own matches.",
  "origin_p1": "This research aims to help beginner competitive Tetris players review their matches and understand mistakes and improvements. The system stores inputs, board states, and attack/defense states during play, then visualizes each decision afterward.",
  "origin_p2": "Lindstedt and Gray (2020) frame Tetris as a fast real-time task and show differences in strategies between novices and experts. This suggests that improving at Tetris involves not only speed, but also strategic choices under cognitive load.",
  "origin_p3": "Alonso-Fernández et al. (2022) show the usefulness of Game Learning Analytics: collecting, analyzing, and visualizing in-game behavior data. This research treats Tetris replay data as learning analytics data to support beginner reflection.",
  "origin_aside_h3": "Research Focus",
  "origin_aside_p": "Replay analysis is the center. Guidebook supplements prerequisite knowledge for interpreting analysis results, and AI is treated as the method for comparing and evaluating each move.",
  "journey_step1_h3": "Record Match Data",
  "journey_step1_p": "Save board states, placements, clears, attacks, time, and operation results for post-match analysis.",
  "journey_step2_h3": "Visualize Each Move",
  "journey_step2_p": "Show board, timeline, attack state, and AI recommendations together so players can locate problematic moments.",
  "journey_step3_h3": "Find Improvements",
  "journey_step3_p": "Compare actual choices with recommended moves to find board deterioration, missed attack chances, and delayed canceling.",
  "journey_step4_h3": "Use Guidebook for Support",
  "journey_step4_p": "Review T-Spins, Combos, canceling, and other prerequisite concepts through small simulations.",
  "journey_step5_h3": "Check Change Over Time",
  "journey_step5_p": "Use match summaries and radar charts to track changes in speed, attack, efficiency, and stability.",
  "replay_p1": "In this system, AI does not direct actions during play. It analyzes player choices after the match, preserving player judgment while supporting reflection.",
  "replay_p2": "Replay lets players inspect board state, placement, line clears, attack output, and field changes for each move, tracing which decisions led to later disadvantage.",
  "replay_p3": "AI evaluation compares actual placements with search-based recommendations. Moves with large gaps are shown as candidates for reflection.",
  "replay_p4": "Match summaries and radar charts also show speed, attack, efficiency, structure, stability, and vision, helping players see long-term change.",
  "guide_p1": "To understand Replay analysis, beginners need basics such as T-Spins, Combos, canceling, attack value, NEXT, and Hold.",
  "guide_p2": "Guidebook breaks rules and techniques into small chapters with animations and fixed-position simulations. Its purpose is to help interpret problems found by Replay.",
  "guide_p3": "For example, when Replay shows a missed T-Spin opportunity, players can return to the T-Spin chapter and practice the structure in a fixed situation.",
  "arch_title_entry": "Data Needed for Analysis",
  "arch_entry_1": "Board snapshots",
  "arch_entry_2": "Inputs and placements",
  "arch_entry_3": "Clears, attacks, canceling",
  "arch_entry_4": "Speed and sequence",
  "arch_connector": "Data recorded during play is reconstructed after the match in Replay and used for AI evaluation and visualization.",
  "arch_layer_3_title": "Analysis & Visualization Layer",
  "arch_layer_3_i1": "Comparison with AI recommendations",
  "arch_layer_3_i2": "Timeline display",
  "arch_layer_3_i3": "Match summary",
  "arch_layer_3_i4": "Radar chart",
  "arch_support_title": "Implementation Notes",
  "arch_support_4_title": "Online Battles",
  "arch_support_4_desc": "Can later expand into a source of evaluation data",
  "tech_p1": "The Replay analysis mechanism and visualization interface are currently implemented. The next step is to evaluate whether beginners can better understand mistakes and improvements through the system.",
  "tech_p2": "Evaluation can test whether players can explain their mistakes, understand recommendations, and reduce repeated error types before and after using the system.",
  "tech_p3": "AI evaluation accuracy also needs improvement. Current scoring uses board height, holes, and attack chances, but the reasons must be translated into beginner-friendly explanations.",
  "tech_p4": "Online battles are not the main topic at this stage; they are positioned as a future extension for collecting richer data. This research first focuses on replay-based reflection support.",
  "tech_card_1_title": "Evaluation Study",
  "tech_card_1_desc": "Check whether beginners can explain mistakes and improvements more easily.",
  "tech_card_2_title": "Analysis Accuracy",
  "tech_card_2_desc": "Validate whether recommendations and scoring truly support improvement.",
  "tech_card_3_title": "Explainability",
  "tech_card_3_desc": "Explain why a move is better using board metrics and natural text.",
  "tech_card_4_title": "Guidebook Link",
  "tech_card_4_desc": "Connect analysis results naturally to relevant basic chapters.",
  "tech_card_5_title": "Data Expansion",
  "tech_card_5_desc": "Add online battle data as a future analysis target."
});

Object.assign(translations["ja"], {
  "cover_h1": "対戦型テトリス初心者の振り返りを支援するリプレイ分析システム",
  "cover_lead": "対戦型テトリスでは、プレイヤーは短時間の中で、ブロックの配置、攻撃、防御、相殺、NEXT と Hold の利用など、複数の要素を同時に判断する必要がある。そのため、初心者は対局後にリプレイを見ても、どの場面で判断を誤ったのか、どのような置き方がより良かったのかを理解しにくい。本研究では、この問題に対して、プレイ中の盤面状態や操作記録を保存し、試合後に一手ごとの判断を可視化するリプレイ分析システムを開発した。",
  "cover_flow_3_title": "システム",
  "cover_flow_3_desc": "リプレイ分析を中心に、操作の問題を可視化し、必要な練習へ導く。",
  "journey_kicker": "システムの全体像",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "回転時にブロックの位置を少しずらし、通常は入らない隙間へ入れる仕組みです。",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "T ブロックを回転で槽に入れ、少ないライン消去から高い攻撃価値を作る代表的な技術です。",
  "origin_p1": "本研究では、対戦型テトリス初心者が自分の対局を振り返り、ミスや改善点を理解できるようにすることを目的とします。そのために、プレイ中の操作記録、盤面状態、攻撃・防御の状況を保存し、試合後に一手ごとの判断を可視化するリプレイ分析システムを開発しました。",
  "origin_p2": "そこで本研究では、リプレイを単なる再生機能ではなく、プレイヤー自身の判断を分析するためのデータとして扱います。盤面状態、操作記録、攻撃・防御の状況を結び付けることで、初心者が「どの一手が問題だったのか」を確認できるようにします。",
  "origin_p3": "また、分析結果を理解するための前提知識として Guidebook を用意し、T-Spin や Combo などの基礎技術を小さなシミュレーションで確認できるようにします。これにより、Replay 分析で見つかった課題を次の練習へ接続します。"
});

Object.assign(translations["zh-CN"], {
  "cover_h1": "面向对战型 Tetris 初学者的 Replay 分析支援系统",
  "cover_lead": "对战型 Tetris 要求玩家在短时间内同时判断方块放置、攻击、防守、抵消、NEXT 与 Hold 等因素。因此，初学者即使赛后观看 replay，也很难理解自己在哪个场面判断错误、怎样放会更好。本研究针对这一问题，开发了保存盘面状态与操作记录，并在赛后可视化每一步判断的 Replay 分析系统。",
  "cover_flow_3_title": "系统",
  "cover_flow_3_desc": "以 Replay 分析为中心，可视化操作问题，并连接到必要练习。",
  "journey_kicker": "系统整体",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "旋转时系统会让方块位置轻微偏移，使它能进入普通移动无法进入的空隙。",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "通过旋转把 T 方块放入槽中，用较少的消行创造较高攻击价值。",
  "origin_p1": "本研究旨在帮助对战型 Tetris 初学者回顾自己的对局，理解错误和改善点。为此，系统保存游玩中的操作记录、盘面状态、攻防状况，并在赛后可视化每一步判断。",
  "origin_p2": "因此，本研究把 replay 视为用于分析玩家自身判断的数据，而不是单纯的播放功能。通过连接盘面状态、操作记录和攻防状况，帮助初学者确认哪一步成为了问题。",
  "origin_p3": "同时，系统准备了 Guidebook 作为理解分析结果的前提知识补充，让玩家通过小型模拟确认 T-Spin、Combo 等基础技术，并把 Replay 分析发现的问题连接到下一次练习。"
});

Object.assign(translations["en"], {
  "cover_h1": "A Replay Analysis Support System for Beginner Competitive Tetris Players",
  "cover_lead": "Competitive Tetris requires players to judge placements, attacks, defense, canceling, NEXT, and Hold within a short time. Beginners often cannot tell, even after watching a replay, where their judgment failed or what placement would have been better. This research develops a Replay analysis system that records board states and inputs during play, then visualizes each decision after the match.",
  "cover_flow_3_title": "System",
  "cover_flow_3_desc": "Replay analysis visualizes decision problems and connects them to necessary practice.",
  "journey_kicker": "System Overview",
  "technique_wall_title": "Wall Kick",
  "technique_wall_desc": "During rotation, the system shifts the piece slightly so it can enter spaces that normal movement cannot reach.",
  "technique_tspin_title": "T-Spin",
  "technique_tspin_desc": "A T piece is rotated into a slot, creating high attack value from a small line clear.",
  "origin_p1": "This research aims to help beginner competitive Tetris players review their matches and understand mistakes and improvements. The system stores inputs, board states, and attack/defense states during play, then visualizes each decision afterward.",
  "origin_p2": "Therefore, replay is treated not as simple playback, but as data for analyzing the player's own decisions. By connecting board states, input records, and attack/defense states, beginners can identify which move became a problem.",
  "origin_p3": "Guidebook is also provided as prerequisite support for understanding the analysis results. Players can review basics such as T-Spins and Combos through small simulations, then connect problems found in Replay analysis to the next practice step."
});

Object.assign(translations["ja"], {
  "nav_journey": "システム",
  "journey_kicker": "システムの全体像",
  "tech_h2": "今後は、本システムが初心者の振り返りを本当に支援できるかを検証する必要があります。",
  "closing_p": "従来は、初心者が自分のリプレイを見ても、具体的にどの判断が問題だったのかを理解しにくいという課題がありました。そこで本研究では、盤面・操作・攻撃状況を記録し、試合後に一手ごとの判断を可視化する Replay 分析システムを開発しました。Guidebook や AI 評価は、この中心目的を支えるための補助要素として位置づけます。"
});

Object.assign(translations["zh-CN"], {
  "nav_journey": "系统",
  "journey_kicker": "系统整体",
  "closing_p": "以往初学者即使观看自己的 replay，也很难理解具体是哪一个判断出了问题。因此本研究开发了记录盘面、操作和攻击状况，并在赛后可视化每一步判断的 Replay 分析系统。Guidebook 与 AI 评价都作为支撑这一中心目的的辅助要素。"
});

Object.assign(translations["en"], {
  "nav_journey": "System",
  "journey_kicker": "System Overview",
  "closing_p": "Traditionally, beginners may watch their own replay but still struggle to understand which decisions were problematic. This research develops a Replay analysis system that records board, input, and attack states, then visualizes each decision after the match. Guidebook and AI evaluation support this central purpose."
});

Object.assign(translations["ja"], {
  "source_tetris_title": "対戦型テトリスにおける操作戦略の差異",
  "source_tetris_desc": "Lindstedt and Gray（2020）は，テトリスを高速なリアルタイム課題として位置づけ，初心者と熟練者の回転操作戦略に差異があることを示している。この知見は，対戦型テトリスにおける上達が単なる反復練習や反応速度だけでなく，認知的負荷を伴う判断過程と関係することを示唆している。",
  "source_gla_title": "Game Learning Analytics に基づくリプレイ分析",
  "source_gla_desc": "Alonso-Fernández et al.（2022）は，シリアスゲームにおけるプレイヤーのインタラクションデータを収集・分析・可視化する Game Learning Analytics の枠組みを示している。本研究では，この知見に基づき，テトリスのリプレイデータを学習過程の分析対象として扱う。",
  "origin_p2": "そこで本研究では，リプレイを単なる再生機能ではなく，プレイヤー自身の判断を分析するためのデータとして扱う。盤面状態，操作記録，攻撃・防御の状況を結び付けることで，初心者が「どの一手が問題だったのか」を確認できるようにする。",
  "origin_p3": "また，分析結果を理解するための前提知識として Guidebook を用意し，T-Spin や Combo などの基礎技術を小さなシミュレーションで確認できるようにする。これにより，Replay 分析で見つかった課題を次の練習へ接続する。",
  "arch_support_4_desc": "オンライン対戦データも収集している",
  "tech_p4": "さらに，オンライン対戦データもすでに収集しており，今後は評価実験や分析対象の拡張に利用できる。本研究では，まずリプレイ分析による初心者の振り返り支援に焦点を絞る。",
  "tech_card_5_title": "オンラインデータ",
  "tech_card_5_desc": "収集済みのオンライン対戦データを評価・分析に活用する。"
});

Object.assign(translations["zh-CN"], {
  "source_tetris_title": "对战型 Tetris 中的操作策略差异",
  "source_tetris_desc": "Lindstedt and Gray（2020）将 Tetris 定位为高速实时任务，并指出初学者与熟练者在旋转操作策略上存在差异。这一研究说明，对战型 Tetris 的进步不仅依赖反复练习或反应速度，也与带有认知负荷的判断过程有关。",
  "source_gla_title": "基于 Game Learning Analytics 的 Replay 分析",
  "source_gla_desc": "Alonso-Fernández et al.（2022）提出了在 serious games 中收集、分析、可视化玩家交互数据的 Game Learning Analytics 框架。本研究基于这一方法，将 Tetris replay 数据作为学习过程的分析对象。",
  "origin_p2": "因此，本研究把 replay 视为用于分析玩家自身判断的数据，而不是单纯的播放功能。通过连接盘面状态、操作记录和攻防状况，帮助初学者确认哪一步成为了问题。",
  "origin_p3": "同时，系统准备了 Guidebook 作为理解分析结果的前提知识补充，让玩家通过小型模拟确认 T-Spin、Combo 等基础技术，并把 Replay 分析发现的问题连接到下一次练习。",
  "arch_support_4_desc": "已经在收集在线对战数据",
  "tech_p4": "此外，在线对战数据已经在收集，之后可以用于评价实验和扩展分析对象。本研究当前仍先聚焦 Replay 分析对初学者复盘的支援。",
  "tech_card_5_title": "在线数据",
  "tech_card_5_desc": "将已收集的在线对战数据用于评价与分析。"
});

Object.assign(translations["en"], {
  "source_tetris_title": "Differences in Operation Strategies in Competitive Tetris",
  "source_tetris_desc": "Lindstedt and Gray (2020) frame Tetris as a fast real-time task and show differences in rotation strategies between novices and experts. This suggests that improvement in competitive Tetris is related not only to repeated practice or reaction speed, but also to decision processes under cognitive load.",
  "source_gla_title": "Replay Analysis Based on Game Learning Analytics",
  "source_gla_desc": "Alonso-Fernández et al. (2022) present Game Learning Analytics as a framework for collecting, analyzing, and visualizing player interaction data in serious games. Based on this perspective, this research treats Tetris replay data as a target for analyzing the learning process.",
  "origin_p2": "Therefore, replay is treated not as simple playback, but as data for analyzing the player's own decisions. By connecting board states, input records, and attack/defense states, beginners can identify which move became a problem.",
  "origin_p3": "Guidebook is also provided as prerequisite support for understanding the analysis results. Players can review basics such as T-Spins and Combos through small simulations, then connect problems found in Replay analysis to the next practice step.",
  "arch_support_4_desc": "Online battle data is already being collected",
  "tech_p4": "Online battle data is also already being collected and can be used in future evaluation studies and expanded analysis. This research first focuses on replay-based reflection support for beginners.",
  "tech_card_5_title": "Online Data",
  "tech_card_5_desc": "Use collected online battle data for evaluation and analysis."
});

Object.assign(translations["ja"], {
  "rules_h2": "初心者は、単なるリプレイ再生だけでは「なぜ負けたのか」「どこを改善すべきか」を理解しにくい。",
  "rules_p2": "また、通常のリプレイ機能は対局を時系列で再生できますが、各手の評価、攻撃・防御への影響、より良い選択肢までは明示しません。そのため初心者は、映像を見返しても「どの場面で判断を誤ったのか」「どのような置き方がより良かったのか」を自力で判断しにくいです。",
  "rules_p3": "盤面の高さ、空洞、攻撃のタイミング、相殺の判断などが同時に関係するため、問題の原因が一手だけに見えないことも多くあります。したがって、リプレイを単なる録画ではなく、一手ごとの判断を可視化する分析データとして扱う支援が必要です。",
  "rules_stack_2_title": "普通のリプレイの限界",
  "rules_stack_2_desc": "再生だけでは、各手の評価や別の選択肢までは示されにくい。",
  "rules_stack_4_desc": "リプレイを、単なる録画ではなく、判断を可視化する分析データとして扱う必要がある。",
  "rules_demo_tspin_desc": "初心者が普通のリプレイから改善点を発見するには、プレイデータに基づく可視化と分析が必要です。"
});

Object.assign(translations["zh-CN"], {
  "rules_h2": "初学者仅靠普通 replay 回放，很难理解“为什么输”和“该改善哪里”。",
  "rules_p2": "普通 replay 可以按时间顺序播放对局，但不会明确显示每一步评价、对攻防的影响或更好的选择。因此初学者即使回看录像，也很难独立判断自己在哪个场面判断错误、怎样放会更好。",
  "rules_p3": "盘面高度、空洞、攻击时机和抵消判断往往同时作用，问题原因不一定只出现在最后一步。因此，需要把 replay 当成可视化每一步判断的分析数据，而不是单纯录像。",
  "rules_stack_2_title": "普通 replay 的局限",
  "rules_stack_2_desc": "单纯播放很难显示每一步评价或其他更好选择。",
  "rules_stack_4_desc": "需要把 replay 当成可视化判断过程的分析数据，而不是普通录像。",
  "rules_demo_tspin_desc": "为了让初学者从普通 replay 中发现改善点，需要基于 play 数据的可视化与分析。"
});

Object.assign(translations["en"], {
  "rules_h2": "Beginners struggle to understand why they lost or what to improve from ordinary replay playback alone.",
  "rules_p2": "Ordinary replay can replay a match chronologically, but it does not explicitly show move evaluation, offensive or defensive impact, or better alternatives. Beginners may therefore rewatch footage without being able to identify where their judgment failed or what placement would have been better.",
  "rules_p3": "Board height, holes, attack timing, and canceling decisions often interact, so the cause is not always a single final move. Replay therefore needs to be treated not as footage alone, but as analysis data that visualizes each decision.",
  "rules_stack_2_title": "Limit of Ordinary Replay",
  "rules_stack_2_desc": "Playback alone rarely shows move evaluation or better alternatives.",
  "rules_stack_4_desc": "Replay must become analysis data that visualizes decisions, not just match footage.",
  "rules_demo_tspin_desc": "Beginners need data-based visualization and analysis to find improvements from ordinary replay."
});

Object.assign(translations["ja"], {
  "cover_lead": "対戦型テトリスでは、プレイヤーは短時間の中で、ブロックの配置、攻撃、防御、相殺、NEXT と Hold の利用など、複数の要素を同時に判断する必要がある。そのため、初心者は普通のリプレイを見返しても、どの場面で判断を誤ったのか、どのような置き方がより良かったのかを理解しにくい。本研究では、この問題に対して、プレイ中の盤面状態や操作記録を保存し、試合後に一手ごとの判断を可視化するリプレイ分析システムを開発した。",
  "cover_flow_2_desc": "初心者は普通のリプレイだけでは、なぜ負けたのか、どこを改善すべきかを理解しにくい。",
  "closing_p": "従来は、初心者が普通のリプレイを見返しても、具体的にどの判断が問題だったのかを理解しにくいという課題がありました。そこで本研究では、盤面・操作・攻撃状況を記録し、試合後に一手ごとの判断を可視化する Replay 分析システムを開発しました。Guidebook や AI 評価は、この中心目的を支えるための補助要素として位置づけます。"
});

Object.assign(translations["zh-CN"], {
  "cover_lead": "对战型 Tetris 要求玩家在短时间内同时判断方块放置、攻击、防守、抵消、NEXT 与 Hold 等因素。因此，初学者即使回看普通 replay，也很难理解自己在哪个场面判断错误、怎样放会更好。本研究针对这一问题，开发了保存盘面状态与操作记录，并在赛后可视化每一步判断的 Replay 分析系统。",
  "cover_flow_2_desc": "初学者仅靠普通 replay，很难理解为什么输、该改善哪里。",
  "closing_p": "以往初学者即使回看普通 replay，也很难理解具体是哪一个判断出了问题。因此本研究开发了记录盘面、操作和攻击状况，并在赛后可视化每一步判断的 Replay 分析系统。Guidebook 与 AI 评价都作为支撑这一中心目的的辅助要素。"
});

Object.assign(translations["en"], {
  "cover_lead": "Competitive Tetris requires players to judge placements, attacks, defense, canceling, NEXT, and Hold within a short time. Beginners often cannot tell, from ordinary replay playback alone, where their judgment failed or what placement would have been better. This research develops a Replay analysis system that records board states and inputs during play, then visualizes each decision after the match.",
  "cover_flow_2_desc": "Beginners struggle to understand why they lost or what to improve from ordinary replay alone.",
  "closing_p": "Traditionally, beginners may rewatch ordinary replay but still struggle to understand which decisions were problematic. This research develops a Replay analysis system that records board, input, and attack states, then visualizes each decision after the match. Guidebook and AI evaluation support this central purpose."
});

const progress = document.querySelector("#scrollProgress");
const navLinks = [...document.querySelectorAll(".toc a")];
const sections = navLinks
  .map((link) => document.querySelector(link.getAttribute("href")))
  .filter(Boolean);

function updateProgress() {
  const max = document.documentElement.scrollHeight - window.innerHeight;
  const ratio = max <= 0 ? 0 : window.scrollY / max;
  progress.style.width = `${Math.min(100, Math.max(0, ratio * 100))}%`;

  let activeId = sections[0]?.id;
  for (const section of sections) {
    const rect = section.getBoundingClientRect();
    if (rect.top <= window.innerHeight * 0.38) {
      activeId = section.id;
    }
  }

  navLinks.forEach((link) => {
    link.classList.toggle("active", link.getAttribute("href") === `#${activeId}`);
  });
}

const revealObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("visible");
      }
    });
  },
  { threshold: 0.12 }
);

document.querySelectorAll(".hero-media, .principle-list div, .journey article, .feature-item, .image-pair figure, .evidence-grid article, .large-shot, .replay-points article, .stats-row figure, .mode-strip article, .arch-node, .tech-stack div").forEach((el) => {
  el.classList.add("reveal");
  revealObserver.observe(el);
});

window.addEventListener("scroll", updateProgress, { passive: true });
window.addEventListener("resize", updateProgress);
updateProgress();

// --- Language Switcher Logic ---

const langBtn = document.getElementById("lang-btn");
const langMenu = document.getElementById("lang-menu");
const langLabel = document.getElementById("current-lang-label");
const langItems = document.querySelectorAll("[data-lang]");

const langNames = {
  "ja": "日本語",
  "zh-CN": "简体中文",
  "en": "English"
};

// Determine initial language: URL ?lang= > localStorage > default "ja"
function getInitialLang() {
  const urlParams = new URLSearchParams(window.location.search);
  const urlLang = urlParams.get("lang");
  if (urlLang && translations[urlLang]) return urlLang;
  const storedLang = localStorage.getItem("app_lang");
  if (storedLang && translations[storedLang]) return storedLang;
  return "ja";
}

let currentLang = getInitialLang();

function setLanguage(lang) {
  if (!translations[lang]) return;
  currentLang = lang;
  document.documentElement.lang = lang;
  localStorage.setItem("app_lang", lang);
  langLabel.textContent = langNames[lang];

  // Update URL query parameter without reloading the page
  const url = new URL(window.location);
  url.searchParams.set("lang", lang);
  history.replaceState(null, "", url);

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });

  // Update active state in menu
  langItems.forEach(btn => {
    if (btn.getAttribute("data-lang") === lang) {
      btn.classList.add("active");
    } else {
      btn.classList.remove("active");
    }
  });
}

langBtn.addEventListener("click", () => {
  const isExpanded = langBtn.getAttribute("aria-expanded") === "true";
  langBtn.setAttribute("aria-expanded", !isExpanded);
  langMenu.classList.toggle("show");
});

langItems.forEach(btn => {
  btn.addEventListener("click", (e) => {
    const selectedLang = e.target.getAttribute("data-lang");
    setLanguage(selectedLang);
    langBtn.setAttribute("aria-expanded", "false");
    langMenu.classList.remove("show");
  });
});

// Close menu on click outside
document.addEventListener("click", (e) => {
  if (!document.getElementById("lang-switcher").contains(e.target)) {
    langBtn.setAttribute("aria-expanded", "false");
    langMenu.classList.remove("show");
  }
});

// Initialize
setLanguage(currentLang);
